USE `zpanel_core` ;
DROP TABLE IF EXISTS `x_translations`;
CREATE TABLE IF NOT EXISTS `x_translations` (
`tr_id_pk` int(11) NOT NULL AUTO_INCREMENT,
`tr_en_tx` text,
`tr_German_tx` text,
`tr_French_tx` text,
PRIMARY KEY (`tr_id_pk`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=562 ;

INSERT INTO `x_translations` (`tr_id_pk`, `tr_en_tx`, `tr_German_tx`, `tr_French_tx`) VALUES
(44, 'Webmail is a convenient way for you to check your email accounts online without the need to configure an email client.', 'Webmail ist ein bequemer Weg fÃ¼r Sie, Ihre E-Mail-Konten online zu Ã¼berprÃ¼fen, ohne dass eine E-Mail-Client zu konfigurieren.', 'Le webmail est un outil pratique qui vous permet de consulter vos comptes e-mails en ligne sans avoir besoin de configurer un logiciel de messagerie.'),
(45, 'Launch Webmail', 'Starten Sie WebMail', 'Ouvrir le webmail'),
(56, 'PHPInfo provides you with information regarding the version of PHP running on this system as well as installed PHP extentsions and configuration details.', 'PHPInfo bietet Ihnen Informationen über die PHP-Version auf dem System, sowie PHP installiert extentsions und Konfigurationsmöglichkeiten.', 'PHPInfo fournit des informations tel que la version de PHP qui s''ex&#233;cute sur votre syst&#232;me, le d&#233;tail de sa configuration ainsi que les extensions install&#233;es.'),
(67, 'From here you can shadow any of your client''s accounts, this enables you to automatically login as the user which enables you to offer remote help by seeing what they see!', 'Von hier aus können alle Ihre Kunden-Accounts können Schatten, ermöglicht Ihnen dies automatisch, wenn der Benutzer mit dem Sie remote helfen zu sehen, was sie sehen, anbieten zu können login!', 'Vous pouvez vous substituer &#224; n''importe quel compte client et vous connecter &#224; son interface, ce qui vous permet d''interagir directement au c&#339;ur du probl&#232;me.'),
(68, 'My Account', 'Meine Konto', 'Mon compte'),
(69, 'Change Password', 'Kennwort ändern', 'Changer le mot de passe'),
(70, 'Shadowing', 'Schatten', 'Substitution'),
(71, 'ZPanel Config', 'Config ZPanel', 'Configuration de ZPanel'),
(72, 'ZPanel News', 'ZPanel Aktuelles', 'Actualit&#233; ZPanel'),
(73, 'Updates', 'Aktualisierung', 'Mises &#224; jour'),
(74, 'Report Bug', 'Fehler melden', 'Signaler un bug'),
(75, 'Account', 'Konto', 'Compte'),
(76, 'Module Admin', 'Modul Admin', 'Module d''administration '),
(77, 'Backup', 'Sicherungskopie', 'Sauvegardes'),
(78, 'Network Tools', 'Netzwerk-Tools', 'Outils r&#233;seau'),
(79, 'Service Status', 'Service Status', 'Statut du service'),
(80, 'PHPInfo', 'PHPInfo', 'PHPInfo'),
(81, 'phpMyAdmin', 'phpMyAdmin', 'phpMyAdmin'),
(82, 'Domains', 'Domains', 'Domaines'),
(83, 'Sub Domains', 'Sub Domains', 'Sous-domaines'),
(84, 'Parked Domains', 'geparkte Domains', 'Domaines gar&#233;s'),
(85, 'Manage Clients', 'Verwalten Kunden', 'G&#233;rer les clients'),
(86, 'Package Manager', 'Paket Manager', 'Gestion des packages'),
(87, 'Server', 'Server', 'Serveur'),
(88, 'Database', 'Datenbank', 'Bases de donn&#233;es'),
(89, 'Advanced', 'Fortgeschritten', 'Avanc&#233;'),
(90, 'Mail', 'Post', 'E-mail'),
(91, 'Reseller', 'Wiederverkäufer', 'Revendeur'),
(92, 'Account Information', 'Account Informationen', 'Informations du compte'),
(93, 'Server Admin', 'Server Admin', 'Administrateur'),
(94, 'Database Management', 'Datenbank Verwalten', 'Gestion des bases de donn&#233;es'),
(95, 'Domain Management', 'Verwalten von Domains', 'Gestion des domaines'),
(96, 'Find out all the latest news and information from the ZPanel project.', 'Finden Sie heraus, alle Neuigkeiten und Informationen aus dem ZPanel Projekt.', 'D&#233;couvrez les toutes derni&#232;res nouvelles et informations du projet ZPanel.'),
(97, 'Check to see if there are any available updates to your version of the ZPanel software.', 'Prüfen Sie, ob es irgendwelche verfügbaren Aktualisierungen für Ihre Version des ZPanel Software.', 'V&#233;rifiez s''il n''y a pas des mises &#224; jour disponibles pour votre version de ZPanel.'),
(98, 'If you have found a bug with ZPanel you can report it here.', 'Did you mean: If you have found a bug with CPanel you can report it here.\r\nWenn Sie einen Fehler mit ZPanel gefunden haben, können Sie ihn hier melden.', 'Si vous avez trouv&#233; un bug avec ZPanel, vous pouvez le rapporter ici.'),
(99, 'phpMyAdmin is a web based tool that enables you to manage your ZPanel MySQL databases via. the web.', 'phpMyAdmin ist ein webbasiertes Tool, das Sie zu Ihrem ZPanel MySQL-Datenbanken via verwalten können. im Internet.', 'phpMyAdmin est une interface qui vous permet de g&#233;rer vos bases de donn&#233;es MySQL via un navigateur.'),
(100, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.', 'Aktuelle persönlichen Daten, die Sie uns mit vorgesehen ist, bitten wir Sie, diese zu halten bis zu Datum, falls wir mit Ihnen Kontakt aufnehmen über Ihre Hosting-Paket erfordern.', 'Ce sont les informations personnelles que vous nous avez transmises. Veuillez les tenir &#224; jour afin que l''on puisse vous contacter &#224; propos de votre h&#233;bergement.'),
(101, 'Webmail is a convenient way for you to check your email accounts online without the need to configure an email client.', 'Webmail ist ein bequemer Weg für Sie, Ihre E-Mail-Konten online zu überprüfen, ohne dass eine E-Mail-Client zu konfigurieren.', 'Le webmail est un outil pratique qui vous permet de consulter vos comptes e-mails en ligne sans avoir besoin de configurer un logiciel de messagerie.'),
(102, 'Change your current control panel password.', 'Ändern Sie Ihre aktuelle Bedienfeld oder MySQL-Kennwort.', 'Changez votre mot de passe actuel.'),
(103, 'The backup manager module enables you to backup your entire hosting account including all your MySQL&reg databases.', 'Der Backup-Manager-Modul ermöglicht es Ihnen, Ihre gesamte Hosting-Account inklusive aller Ihrer MySQL &reg Datenbank-Backup.', 'Le module de gestion de sauvegardes vous permet de sauvegarder tout votre compte d''h&#233;bergement (FTP, bases de donn&#233;es, E-mails...)'),
(104, 'You can use the tools below to diagnose issues or to simply test connectivity to other servers or sites around the globe.', 'Sie können die folgenden Tools verwenden, um Probleme zu diagnostizieren oder einfach testen Verbindung mit anderen Servern oder Websites rund um den Globus.', 'Vous pouvez utiliser les outils ci-dessous pour diagnostiquer les probl&#232;mes ou tout simplement pour tester la connectivit&#233; &#224; d''autres serveurs ou des sites &#224; travers le monde.'),
(105, 'Here you can check the current status of our services and see what services are up and running and which are down and not.', 'Hier können Sie den aktuellen Status unserer Dienstleistungen und sehen, welche Dienste vorhanden sind und laufen, und die nach unten und es nicht sind.', 'Ici vous pouvez v&#233;rifier le statut actuel des services du serveur et voir lesquels sont en fonctionnement et ceux qui ne le sont pas.'),
(106, 'This module enables you to add or configure domain web hosting on your account.', 'Dieses Modul ermöglicht es Ihnen, hinzuzufügen oder zu konfigurieren Domain Hosting auf Ihrem Konto.', 'Ce module vous permet d''ajouter ou configurer un domaine &#224; h&#233;berger sur votre compte.'),
(107, 'Domain parking refers to the registration of an Internet domain name without that domain being used to provide services such as e-mail or a website. If you have any domains that you are not using, then simply park them!', 'Domain-Parking bezieht sich auf die Registrierung von Internet Domain-Namen ohne diese Domäne verwendet, um Dienste wie E-Mail oder eine Webseite bereitzustellen. Wenn Sie alle Domains, die Sie nicht haben, dann einfach parken sie!', 'La fonctionnalit&#233; des domaines gar&#233;s vous permet d''ajouter un domaine sans que celui-ci soit visible sur le web. Pratique pour r&#233;server un domaine qui ne sera pas utilis&#233; imm&#233;diatement.'),
(108, 'This module enables you to add or configure domain web hosting on your account.', 'Dieses Modul ermöglicht es Ihnen, hinzuzufügen oder zu konfigurieren Domain Hosting auf Ihrem Konto.', 'Ce module vous permet d''ajouter ou configurer un domaine &#224; h&#233;berger sur votre compte.'),
(109, 'Administer or configure modules registered with module admin', 'Verwalten oder zu konfigurieren Module mit Modul admin registriert', 'Administrer ou configurer des modules install&#233;s avec le gestionnaire de modules.'),
(110, 'The account manager enables you to view, update and create client accounts.', 'Die Account-Manager ermöglicht es Ihnen, anzuzeigen, zu aktualisieren und erstellen Kundenkonten.', 'Le gestionnaire de compte vous permet de visualiser, mettre &#224; jour et cr&#233;er des comptes clients.'),
(111, 'Welcome to the Package Manager, using this module enables you to create and manage existing reseller packages on your ZPanel hosting account.', 'Willkommen auf der Paket-Manager, mit diesem Modul ermöglicht Ihnen die Erstellung und Verwaltung von bestehenden Reseller-Pakete auf Ihrem ZPanel Hosting-Account.', 'Bienvenue dans le gestionnaire de paquets. Ce module vous permet de cr&#233;er et g&#233;rer les paquets clients revendeur existant sur votre compte ZPanel.'),
(112, 'Gives you access to your files with drag-and-drop, multiple file uploading, text editing, zip support.', 'Ermöglicht den Zugriff auf Ihre Dateien mit Drag-and-drop, multiple Datei-Upload, Textbearbeitung, zip unterstützen.', 'Cette fonction vous donne acc&#232;s &#224; vos fichiers par simple glisser-d&#233;poser, le t&#233;l&#233;chargement de fichiers multiples, l''&#233;dition de texte, le support zip.'),
(113, 'Secure FTP Applet is a JAVA based FTP client component that runs within your web browser. It is designed to let non-technical users exchange data securely with an FTP server.', 'Secure FTP Applet ist eine Java-basierte FTP-Client-Komponente, die in Ihrem Web-Browser läuft. Es wurde entwickelt, um nicht-technische Anwender den Datenaustausch secureiy lassen mit einem FTP-Server.', 'L''application Secure FTP est un client FTP bas&#233; sur JAVA qui permet de fonctionner sans votre votre navigateur. Il est recommand&#233; pour les transferts s&#233;curis&#233;s avec le serveur FTP.'),
(114, 'Full name', 'Vollständiger Name', 'Nom et pr&#233;nom'),
(115, 'Email Address', 'E-Mail Adresse', 'Adresse E-mail'),
(116, 'Phone Number', 'Telefonnummer', 'Num&#233;ro de t&#233;l&#233;phone'),
(117, 'Choose Language', 'Sprache wählen', 'Choisissez la langue'),
(118, 'Postal Address', 'Postanschrift', 'Adresse postale'),
(119, 'Postal Code', 'Postleitzahl', 'Code postal'),
(120, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.', 'Aktuelle persönlichen Daten, die Sie uns mit vorgesehen ist, bitten wir Sie, diese zu halten bis zu Datum, falls wir mit Ihnen Kontakt aufnehmen über Ihre Hosting-Paket erfordern.', 'Ce sont les informations personnelles que vous nous avez transmises. Veuillez les tenir &#224; jour afin que l''on puisse vous contacter &#224; propos de votre h&#233;bergement.'),
(121, 'Changes to your account settings have been saved successfully!', 'Änderungen an Ihrem Konto-Einstellungen wurden erfolgreich gespeichert!', 'Modifications prises en compte avec succ&#232;s !'),
(122, 'Update Account', 'Aktualisierung Konto', 'Mettre &#224; jour mon compte'),
(123, 'Enter your account details', 'Geben Sie Ihre Kontodaten', 'Entrez vos informations de compte'),
(124, 'Usage Viewer', NULL, 'Statistiques d''utilisation'),
(125, 'Admin', NULL, 'Administrateur'),
(126, 'phpSysInfo', NULL, 'phpSysInfo'),
(127, 'Cron Manager', NULL, 'Gestionnaire de t&#226;ches Cron'),
(128, 'FAQ''s', NULL, 'FAQ'),
(129, 'Protect Directories', NULL, 'Prot&#233;ger un r&#233;pertoire'),
(130, 'Webalizer Stats', NULL, 'Statistiques Webalizer'),
(131, 'MySQL Database', NULL, 'Bases de donn&#233;es MySQL'),
(132, 'MySQL Users', NULL, 'Utilisateurs MySQL'),
(133, 'Domain', NULL, 'Domaines'),
(134, 'DNS Manager', NULL, 'Gestionnaire DNS'),
(135, 'Aliases', NULL, 'Alias'),
(136, 'Distribution Lists', NULL, 'Listes de distribution'),
(137, 'Forwards', NULL, 'Redirections'),
(138, 'Mailboxes', NULL, 'Bo&#238;tes mails'),
(139, 'WebMail', NULL, 'WebMail'),
(140, 'Client Notice Manager', NULL, 'Notification clients'),
(141, 'Manage Groups', NULL, 'G&#233;rer les groupes'),
(142, 'Theme Manager', NULL, 'G&#233;rer les th&#232;mes'),
(143, 'File', NULL, 'Fichier'),
(144, 'FTP Accounts', NULL, 'Comptes FTP'),
(145, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.\r\n', NULL, 'Ce sont les informations personnelles que vous nous avez transmises. Veuillez les tenir &#224; jour afin que l''on puisse vous contacter &#224; propos de votre h&#233;bergement.'),
(146, 'The account usage screen enables you to see exactly what you are currently using on your hosting package.', NULL, 'Cette interface vous permet de visualiser les ressources utilis&#233;es et celles restantes sur votre h&#233;bergement.'),
(147, 'phpSysInfo is a web-based server hardware monitoring tool which enables you to see detailed hardware statistics of your server.', NULL, 'phpSysInfo est un outil de surveillance hardware qui vous permet de voir les statistiques d&#233;taill&#233;es sur le mat&#233;riel de votre serveur via une page web.'),
(148, 'Changes made here affect the entire ZPanel configuration, please double check everything before saving changes.', NULL, 'Ces changements peuvent avoir un impact sur la configuration de ZPanel, veuillez rev&#233;rifiez avant de proc&#233;der &#224; la sauvegarde.'),
(149, 'Here you can configure PHP scripts to run automatically at different time intervals.', NULL, 'Ici vous pouvez configurer des scripts PHP pour qu''ils s&#8217;ex&#233;cutent automatiquement &#224; des intervalles de temps diff&#233;rents.'),
(150, 'Please find a list of the most common questons from users, if you are unable to find a solution to your problem below please then contact your hosting provider. Simply click on the FAQ below to view the solution.', NULL, 'Voici les questions fr&#233;quemment pos&#233;es par les utilisateurs. Cliquez sur une question pour voir la r&#233;ponse. Si vous ne trouvez pas la r&#233;ponse &#224; votre probl&#232;me, contactez le support technique.'),
(151, 'This module enables you to configure .htaccess files and users to protect your web directories.', NULL, 'Ce module vous permet de prot&#233;ger un r&#233;pertoire, donnant ainsi l''acc&#232;s &#224; des utilisateurs cibl&#233;s (pr&#233;c&#233;demment cr&#233;&#233;s)'),
(152, 'You can view many statistics such as visitor infomation, bandwidth used, referal infomation and most viewed pages etc. Web stats are based on Domains and sub-domains so to view web stats for a particular domain or subdomain use the drop-down menu to select the domain or sub-domain you want to view web stats for.', NULL, 'S&#233;lectionnez le domaine / sous-domaine pour consulter les statistiques compl&#232;tes.'),
(153, 'MySQL&reg databases are used by many PHP applications such as forums and ecommerce systems, below you can manage and create MySQL&reg databases.', NULL, 'G&#233;rez vos bases de donn&#233;es MySQL&#174;'),
(154, 'MySQL&reg Users allows you to add users and permissions to your MySQL&reg databases.', NULL, 'G&#233;rez vos utilisateurs MySQL&#174;'),
(155, 'Using this module you have the ability to create alias mailboxes to existing accounts.', NULL, 'G&#233;rez vos alias d''adresses mail'),
(156, 'This module enables you to create and manage email distribution groups.', NULL, 'G&#233;rez vos listes de distribution.'),
(157, 'Using this module you have the ability to create mail forwarders.', NULL, 'G&#233;rez vos redirections mail.'),
(158, 'Using this module you have the ability to create IMAP and POP3 Mailboxes.', NULL, 'G&#233;rez vos adresses mail.'),
(159, 'Enables resellers to set global notices for their clients.', NULL, 'G&#233;rez le message affich&#233; aux clients.'),
(160, 'Manage user groups to enable greater control over module permission.', NULL, 'G&#233;rez les groupes d''utilisateurs (pratique pour les modules).'),
(161, 'Enables the reseller to set themes configurations for their clients.', NULL, 'G&#233;rez vos th&#232;mes clients (ZPanel)'),
(162, 'File Management', NULL, 'Gestion des fichiers'),
(163, 'Using this module you can create FTP accounts which will enable you and any other accounts you create to have the ability to upload and manage files on your hosting space.', NULL, 'G&#233;rez vos comptes FTP'),
(164, 'Main Page', NULL, 'Page d''ccueil'),
(165, 'Log off ZPanel', NULL, 'D&#233;connexion du panel'),
(166, 'Server time is', NULL, 'Il est actuellement '),
(167, 'Home', NULL, 'Accueil'),
(168, 'Log Out', NULL, 'D&#233;connexion'),
(169, 'Username', NULL, 'Nom d''utilisateur'),
(170, 'Update your contact email address', NULL, 'Veuillez mettre &#224; jour votre adresse mail de contact.'),
(171, 'Package name', NULL, 'Nom du pack'),
(172, 'Account type', NULL, 'Type de compte'),
(173, 'Last Logon', NULL, 'Derni&#232;re connexion'),
(174, 'Disk Quota', NULL, 'Quota du disque'),
(175, 'Bandwidth Quota', NULL, 'Quota de bande passante'),
(176, 'Used', NULL, 'Utilis&#233;'),
(177, 'Max', NULL, 'Maximum'),
(178, 'Sub-domains', NULL, 'Sous-domaines'),
(179, 'MySQL&reg; databases', NULL, 'Base de donn&#233;es MySQL'),
(180, 'Email Accounts', NULL, 'Comptes mails'),
(181, 'Email Forwarders', NULL, 'Redirections de mails'),
(182, 'Server Information', NULL, 'Informations sur le serveur'),
(183, 'Your IP', NULL, 'Votre IP'),
(184, 'Server IP', NULL, 'IP du serveur'),
(185, 'Server OS', NULL, 'OS du serveur'),
(186, 'Apache Version', NULL, 'Version d''Apache'),
(187, 'PHP Version', NULL, 'Version de PHP'),
(188, 'MySQL Version', NULL, 'Version de MySQL'),
(189, 'ZPanel Version', NULL, 'Version du Panel'),
(190, 'Server uptime', NULL, 'Serveur ON depuis '),
(191, 'Domain Information', NULL, 'Informations du domaine'),
(192, 'Administration Modules', NULL, 'Administration des modules'),
(193, 'Apache Config', NULL, 'Configuration d''Apache'),
(194, 'Backup Config', NULL, 'Configuration des sauvegardes'),
(195, 'DNS Config', NULL, 'Configuration DNS'),
(196, 'FTP Config', NULL, 'Configuration FTP'),
(197, 'Mail Config', NULL, 'Configuration des mails'),
(198, 'Configure Modules', NULL, 'Configurer les modules'),
(199, 'Module', NULL, 'Module'),
(200, 'On', NULL, 'Activ&#233;'),
(201, 'Off', NULL, 'D&#233;sactiv&#233;'),
(202, 'Category', NULL, 'Cat&#233;gorie'),
(203, 'Up-to-date?', NULL, 'A jour ?'),
(204, 'Enabled', NULL, 'Activ&#233;'),
(205, 'Disabled', NULL, 'D&#233;sactiv&#233;'),
(206, 'N/A (Module Admin)', NULL, 'N/A (Module administrateur)'),
(207, 'Save changes', NULL, 'Sauvegarder'),
(208, 'Module Information', NULL, 'Informations du module'),
(209, 'Module name', NULL, 'Nom du module'),
(210, 'Module description', NULL, 'Description du module'),
(211, 'Module developer', NULL, 'D&#233;veloppeur du module'),
(212, 'Module version', NULL, 'Version du module'),
(213, 'Latest Version', NULL, 'Derni&#232;re version'),
(214, 'Module Type', NULL, 'Type du module'),
(215, 'Install a new module', NULL, 'Installer un nouveau module'),
(216, 'You can automatically install a new module by uploading your zpanel package archive (.zpp file) and then click ''Install'' to begin the process.', NULL, 'Vous pouvez installer automatiquement un nouveau module en envoyant l''archive de votre paquet zpanel (fichier .zpp) puis en cliquant sur "Installer".rnrnL''installation d&#233;butera automatiquement.'),
(217, 'Install!', NULL, 'Installer !'),
(218, 'Manage Domains', NULL, 'G&#233;rez les domaines'),
(219, 'Choose fom the list of domains below', NULL, 'Choisissez parmi cette liste'),
(220, 'Select a domain', NULL, 'S&#233;lectionnez un domaine'),
(221, 'Select', NULL, 'S&#233;lectionner'),
(222, 'Power Plug', NULL, 'Plugin On/Off'),
(223, 'Changes to your module options have been saved successfully!', NULL, 'Modifications du module prises en compte !'),
(224, 'Power Plug is a simple module that enables you to shutdown or restart your server from the ZPanel web interface.', NULL, 'Le module Plugin On/Off permet d''arr&#234;ter - red&#233;marrer le serveur via le panel.'),
(225, 'FTP Browser', NULL, 'Navigateur FTP'),
(226, 'Secure FTP Applet is a JAVA based FTP client component that runs within your web browser. It is designed to let non-technical users exchange data security with an FTP server.', NULL, 'L''applet FTP Secure de JAVA permet un &#233;change de donn&#233;es s&#233;curis&#233;.'),
(227, 'Launch phpSysInfo', NULL, 'Lancer phpSysInfo'),
(228, 'Select the client you wish to shadow', NULL, 'S&#233;lectionnez le client que vous souhaitez visualiser'),
(229, 'Package', NULL, 'Pack d''h&#233;bergement'),
(230, 'Group', NULL, 'Groupe'),
(231, 'Current Disk', NULL, 'Espace disque actuel'),
(232, 'Current Bandwidth', NULL, 'Bande passante actuelle'),
(233, 'Shadow', NULL, 'Suivre'),
(234, 'You have no Clients at this time.', NULL, 'Aucun client enregistr&#233;.'),
(235, 'As a reseller you can configure theme settings for your clients. If the theme you select has multiple CSS versions you will be prompted for which theme ''version'' you would like to use after you ''save'' the changes.', NULL, 'En tant que revendeur, vous pouvez configurer les param&#232;tres de th&#232;me pour vos clients. Si le th&#232;me que vous s&#233;lectionnez poss&#232;de plusieurs versions CSS, vous devrez selectionner quelle "version" de th&#232;me vous souhaitez utiliser apr&#232;s avoir sauvegard&#233; les changements.'),
(236, 'Select a theme', NULL, 'S&#233;lectionnez un th&#232;me'),
(237, 'Theme name', NULL, 'Nom du th&#232;me'),
(238, 'Save', NULL, 'Sauvegarder'),
(239, 'Theme variation', NULL, 'Variante du th&#232;me'),
(240, 'Update', NULL, 'Mise &#224; jour'),
(241, 'Delete', NULL, 'Supprimer'),
(242, 'Please confirm that you want to delete this domain.', NULL, 'Confirmez la suppression du domaine'),
(243, 'Cancel', NULL, 'Annuler'),
(244, 'Current domains', NULL, 'Domaines actuels'),
(245, 'Domain name', NULL, 'Nom de domaine'),
(246, 'Home directory', NULL, 'R&#233;pertoire racine'),
(247, 'Status', NULL, 'Statut'),
(248, 'You currently do not have any domains configured. Create a domain using the form below.', NULL, 'Vous n''avez enregistr&#233; aucun nom de domaine. Enregistrez-en un ci-dessous.'),
(249, 'Create a new home directory', NULL, 'Cr&#233;ez un nouveau r&#233;pertoire racine'),
(250, 'Use existing home directory', NULL, 'Utiliser un r&#233;pertoire racine existant'),
(251, 'You have reached your domain limit!', NULL, 'Vous avez atteint votre limite de domaines !'),
(252, 'Changes to your domain web hosting has been saved successfully.', NULL, 'Modifications prises en compte avec succ&#232;s.'),
(253, 'Pending', NULL, 'En attente'),
(254, 'Your domain will become active at the next scheduled update. This can take up to one hour.', NULL, 'Votre domaine sera actif sous peu.rnAu maximum, cela peut prendre une heure.rnSi au bout de 24 heures, votre domaine est toujours en attente, contactez le support technique.'),
(255, 'Create Deafult DNS Records', NULL, 'Cr&#233;er les enregistrements DNS par d&#233;faut'),
(256, 'No records were found for this domain. Click the button below to set up your domain records for the first time', NULL, 'Aucun enregistrement trouv&#233; pour ce domaine. Cliquez sur le bouton ci-dessous pour configurer les premiers enregistrements de votre domaine'),
(257, 'Create Records', NULL, 'Cr&#233;er un enregistrement'),
(258, 'Your DNS zone has been loaded without errors.', NULL, 'Votre zone DNS a &#233;t&#233; charg&#233;e avec succ&#232;s !'),
(259, 'DNS records for', NULL, 'Enregistrements DNS pour'),
(260, 'Undo Changes', NULL, 'Annuler les changements'),
(261, 'Domain List', NULL, 'Liste des domaines'),
(262, 'The A record contains an IPv4 address. It''s target is an IPv4 address, e.g. ''192.168.1.1''.', NULL, 'L''enregistrement A contient une adresse IP interne. Il doit contenir une adresse IP externe. rnExemple : "92.247.51.284"'),
(263, 'Host Name', NULL, 'Nom d''h&#244;te'),
(264, 'Target', NULL, 'Cible'),
(265, 'Actions', NULL, 'Actions'),
(266, 'Add New Record', NULL, 'Ajouter un nouvel enregistrement'),
(267, 'The AAAA record contains an IPv6 address. It''s target is an IPv6 address, e.g. ''2607:fe90:2::1''.', NULL, 'L''enregistrement AAAA doit contenir une adresse IPv6. rnPar exemple : "2607:fe90:2::1"'),
(268, 'The CNAME record specifies the canonical name of a record. It''s target is a fully qualified domain name, e.g. \r\n''webserver-01.example.com''.', NULL, 'L''enregistrement CNAME est en fait une copie d''un autre nom de domaine.'),
(269, 'The MX record specifies a mail exchanger host for a domain. Each mail exchanger has a priority or preference that is a numeric value between 0 and 65535. It''s target is a fully qualified domain name, e.g. ''mail.example.com''.', NULL, 'L''enregistrement MX sp&#233;cifie un serveur de messagerie pour un domaine. Chaque serveur de messagerie a une priorit&#233; ou pr&#233;f&#233;rence qui est une valeur num&#233;rique entre 0 et 65535. Il doit contenir un nom de domaine pleinement qualifi&#233;. Par exemple : "mail.example.com".'),
(270, 'Priority', NULL, 'Priorit&#233;'),
(271, 'The TXT field can be used to attach textual data to a domain.', NULL, 'Le champ TXT peut &#234;tre utilis&#233; pour attacher des donn&#233;es textuelles &#224; un domaine.'),
(272, 'SRV records can be used to encode the location and port of services on a domain name. It''s target is a fully qualified domain name, e.g. ''host.example.com''.', NULL, 'L''enregistrements SRV peut &#234;tre utilis&#233; pour coder l''emplacement et le port de services sur un nom de domaine. Il doit contenir un nom de domaine pleinement qualifi&#233;. Par exemple : "host.example.com".'),
(273, 'Weight', NULL, 'Poids'),
(274, 'Port', NULL, 'Port'),
(275, 'SPF records is used to store Sender Policy Framework details. It''s target is a text string, e.g.<br>''v=spf1 a:192.168.1.1 include:example.com mx ptr -all'' (Click <a href="http://www.microsoft.com/mscorp/safety/content/technologies/senderid/wizard/" target="_blank">HERE</a> for the Microsoft SPF Wizard.)', NULL, 'L''enregistrements SPF est utilis&#233; pour stocker les d&#233;tails du "Sender Policy Framework". Il doit contenir une cha&#238;ne de texte. Exemple :rn''v=spf1 a:127.0.0.1 include:example.com mx ptr -all'' (Clicquer <a href="http://www.microsoft.com/mscorp/safety/content/technologies/senderid/wizard/">ici</a> pour l''assistant Microsoft SPF.)'),
(276, 'Nameserver record. Specifies nameservers for a domain. It''s target is a fully qualified domain name, e.g. ''ns1.example.com''. The records should match what the domain name has registered with the internet root servers.', NULL, 'L''enregistrement NS vous est communiqu&#233; par votre h&#233;bergeur (si autre que HabbHeberg).'),
(277, 'Please note that changes to your zone records can take up to 24 hours before they become ''live''.', NULL, 'Les modifications DNS peuvent mettre 24 heures avant d''&#234;tre effectives (temps de propagation DNS)'),
(278, 'Output of DNS zone checker:', NULL, 'Rapport de v&#233;rification de la zone DNS :'),
(279, 'Live', NULL, 'Actif'),
(280, 'Changes to your DNS have been saved successfully!', NULL, 'Les modifications apport&#233;es &#224; vos DNS ont &#233;t&#233; sauvegard&#233;es avec succ&#232;s !'),
(281, 'Delete package', NULL, 'Supprimer le pack'),
(282, 'Please confirm and choose a package to move any existing clients to before the selected package is deleted.', NULL, 'Choisissez un paquet dans lequel tous les clients du paquet &#224; supprimer seront transf&#233;r&#233;s.'),
(283, 'Package to delete', NULL, 'paquet &#224; supprimer'),
(284, 'Move current package members to', NULL, 'Transf&#233;rer les clients du paquet vers'),
(285, 'Edit package', NULL, 'Modifier le paquet '),
(286, 'Enable PHP', NULL, 'Activer PHP'),
(287, 'Enable CGI', NULL, 'Activer CGI'),
(288, 'No. Domains', NULL, 'Nombre de domaines'),
(289, 'No. Sub-domains', NULL, 'Nombre de sous domaines'),
(290, 'No. Parked domains', NULL, 'Nombre de domaine r&#233;serv&#233;s'),
(291, 'No. Mailboxes', NULL, 'Nombre d''adresses mail'),
(292, 'No. Forwarders', NULL, 'Nombre de redirections d''emails'),
(293, 'No. Dist Lists', NULL, 'Nombre de liste de distribution'),
(294, 'No. FTP accounts', NULL, 'Nombre de comptes FTP'),
(295, 'No. MySQL databases', NULL, 'Nombre de base de donn&#233;es MySQL'),
(296, 'Disk space quota', NULL, 'Quota d''espace disque'),
(297, 'Monthly bandwidth quota', NULL, 'Quota de bande passante mensuelle'),
(298, 'Created', NULL, 'Cr&#233;er'),
(299, 'No. of clients', NULL, 'Nombre de clients'),
(300, 'Edit', NULL, 'Modifier'),
(301, 'You have no packages at this time. Create a package using the form below.', NULL, 'Aucun pack. Cr&#233;ez-en un ci-dessous.'),
(302, 'Create a new package', NULL, 'Cr&#233;er un nouveau pack.'),
(303, 'Administration', NULL, 'Administration'),
(304, 'Demo', NULL, 'D&#233;mo'),
(305, 'Changes to your packages have been saved successfully!', NULL, 'Les modifications apport&#233;es &#224; vos packs ont &#233;t&#233; sauvegard&#233;es avec succ&#232;s!'),
(306, 'This module enables you to manage user groups for your client, User groups enable you to control what modules your users can see and access. ', NULL, 'G&#233;rez les groupes d''utilisateurs (pratique pour les modules)'),
(307, 'Delete user group', NULL, 'Supprimer groupe d''utilisateurs'),
(308, 'Please confirm and choose a group to move any existing clients to before the selected group is deleted.', NULL, 'D&#233;placer les clients du groupe en suppression vers le groupe'),
(309, 'Please confirm that you want to delete this group.', NULL, 'Confirmer la suppression de ce groupe'),
(310, 'Move current group members to', NULL, 'D&#233;placement des membres du groupe en cours'),
(311, 'Default user groups', NULL, 'Groupe d''utilisateurs par d&#233;faut'),
(312, 'Users', NULL, 'Utilisateurs'),
(313, 'Description ', NULL, 'Description'),
(314, 'Current user groups', NULL, 'Groupes d''utilisateurs actuels'),
(315, 'There are currently no custom user groups configured!', NULL, 'Aucun groupe d''utilisateurs'),
(316, 'Create new user group', NULL, 'Cr&#233;er un groupe d''utilisateurs'),
(317, 'Group name', NULL, 'Nom du groupe'),
(318, 'Description', NULL, 'Description'),
(319, 'Create', NULL, 'Cr&#233;er'),
(320, 'Edit user group', NULL, 'Editer le groupe d''utilisateur'),
(321, 'Administrators', NULL, 'Administrateurs'),
(322, 'The main administration group, this group allows access to all areas of ZPanel.', NULL, 'Groupe de SU (acc&#232;s &#224; toutes les fonctions du Panel).'),
(323, 'Resellers', NULL, 'Revendeurs'),
(324, 'Resellers have the ability to manage, create and maintain user accounts within ZPanel.', NULL, 'Les revendeurs peuvent g&#233;rer et cr&#233;er des packs et des utilisateurs'),
(325, 'Users have basic access to ZPanel.', NULL, 'Les utilisateurs ont un acc&#232;s basique au Panel.'),
(326, 'Checking if your version of ZPanel is up to date...', NULL, 'V&#233;rifier une mise &#224; jour'),
(327, 'Delete database', NULL, 'Supprimer la base de donn&#233;es'),
(328, 'Please confirm that you want to delete this database.', NULL, 'Confirmer la suppression de cette base de donn&#233;es.'),
(329, 'Current MySQL&reg Databases', NULL, 'Bases de donn&#233;es MySQL&#174; Actuelles'),
(330, 'Database name', NULL, 'Nom de la base'),
(331, 'Size', NULL, 'Taille'),
(332, 'You have no databases at this time. Create a database using the form below.', NULL, 'Aucune base de donn&#233;es, cr&#233;ez-en une ci-dessous.'),
(333, 'Create a new MySQL&reg database', NULL, 'Cr&#233;er une nouvelle base de donn&#233;es MySQL&#174;'),
(334, 'You have reached your MySQL database limit!', NULL, 'Vous avez atteint votre limite de base de donn&#233;es MySQL&#174;'),
(335, 'Delete User', NULL, 'Supprimer un utilisateur'),
(336, 'Please confirm that you want to delete this MySQL user.', NULL, 'Confirmer la suppression de l''utilisateur MySQL&#174;'),
(337, 'Databases for user', NULL, 'Bases de donn&#233;es pour l''utilisateur'),
(338, 'Remove from user', NULL, 'Supprimer l''utilisateur'),
(339, 'Remove database', NULL, 'Supprimer la base de donn&#233;es'),
(340, 'This user currently has no databases. Assign a database using the form below.', NULL, 'Aucune base de donn&#233;es pour cet utilisateur, attribuez-lui en une.'),
(341, 'Add Database', NULL, 'Ajouter la base de donn&#233;es'),
(342, 'Reset Password', NULL, 'R&#233;initialiser le mot de passe'),
(343, 'Password', NULL, 'Mot de passe'),
(344, 'Save Password', NULL, 'Sauvegarder le mot de passe'),
(345, 'Generate Password', NULL, 'G&#233;n&#233;rer un mot de passe'),
(346, 'Current MySQL&reg Users', NULL, 'Utilisateurs actuels de MySQL&#174;'),
(347, 'User name', NULL, 'Nom d''utilisateur'),
(348, 'Access', NULL, 'Acc&#232;s'),
(349, 'Databases', NULL, 'Bases de donn&#233;es'),
(350, 'You have no MySQL&reg users at this time. Create a user using the form below.', NULL, 'Aucun utilisateur MySQL&#174;.rnCr&#233;ez-en un ci-dessous.'),
(351, 'Create a new MySQL&reg User', NULL, 'Cr&#233;er un utilisateur MySQL&#174;'),
(352, 'Map Database', NULL, 'Plan de la base de donn&#233;es'),
(353, 'Remote Access', NULL, 'Acc&#232;s &#224; distance'),
(354, 'Allow from any IP', NULL, 'Depuis n''importe quelle adresse IP'),
(355, 'Only from single IP', NULL, 'Seulement depuis une adresse IP'),
(356, 'Databases Usage', NULL, 'Utilisation des bases de donn&#233;es'),
(357, 'Launch phpMyAdmin', NULL, 'Lancer phpMyAdmin'),
(358, 'Enter your current and new password', NULL, 'Entrez votre mot de passe actuel ainsi que le nouveau'),
(359, 'Current password', NULL, 'Mot de passe actuel'),
(360, 'New password', NULL, 'Nouveau mot de passe'),
(361, 'Confirm new password', NULL, 'Confirmer le nouveau mot de passe'),
(362, 'Change', NULL, 'Sauvegarder'),
(363, 'Disk Usage Total', NULL, 'Total d''utilisation des disques'),
(364, 'Package Usage Total', NULL, 'Total d''utilisation du pack'),
(365, 'Disk space', NULL, 'Espace disque'),
(366, 'Bandwidth', NULL, 'Bande passante'),
(367, 'MySQL&reg databases', NULL, 'Bases de donn&#233;es MySQL &#174;'),
(368, 'Mail forwarders', NULL, 'Transitaires d'' E-mail'),
(369, 'Domain Usage', NULL, 'Utilisation des domaines'),
(370, 'Sub-Domain Usage', NULL, 'Utilisation des sous-domaines'),
(371, 'Parked-Domain Usage', NULL, 'Utilisation des domaines r&#233;serv&#233;s'),
(372, 'MySQL&reg Database Usage', NULL, 'utilisation des base de donn&#233;es MySQL&#174;'),
(373, 'FTP Usage', NULL, 'Utilisation FTP'),
(374, 'Mailbox Usage', NULL, 'Utilisation des bo&#238;tes mail'),
(375, 'Forwarders Usage', NULL, 'Utilisation des redirections'),
(376, 'Distribution List Usage', NULL, 'Utilisation des listes de distribution'),
(377, 'Power Options', NULL, 'Options d''alimentation'),
(378, 'Do it!', NULL, 'Do it !'),
(379, 'Configure your ZPanel Settings', NULL, 'Configurer les param&#232;tres du panel'),
(380, 'ZPanel Daemon', NULL, 'Mise &#224; jour configuration serveur'),
(381, 'Next Daemon Run', NULL, 'Prochain Daemon'),
(382, 'Never', NULL, 'Jamais'),
(383, 'Last Daemon Run', NULL, 'Ex&#233;cuter le dernier Daemon'),
(384, 'Last Day Daemon Run', NULL, 'Dernier lancement Daemon (j)'),
(385, 'Last Week Daemon Run', NULL, 'Dernier lancement Daemon (s)'),
(386, 'Last Month Daemon Run', NULL, 'Dernier lancement Daemon (m)'),
(387, 'Queue a full daemon run (reset)', NULL, 'R&#233;initialiser les demandes de configuration'),
(388, 'Go', NULL, 'Aller'),
(389, 'Run Daemon Now', NULL, 'Ex&#233;cuter le Daemon'),
(390, 'Date Format', NULL, 'Format de date'),
(391, 'Set the date format used by modules.', NULL, 'R&#233;gler le format de date utilis&#233; par les modules.'),
(392, 'From Address', NULL, 'Depuis l'' Adresse'),
(393, 'The email address to appear in the From field of emails sent by ZPanel.', NULL, 'Adresse mail exp&#233;ditrice des mails depuis le Panel'),
(394, 'From Name', NULL, 'De '),
(395, 'The name to appear in the From field of emails sent by ZPanel.', NULL, 'Nom de l''exp&#233;diteur des mails depuis le Panel'),
(396, 'Icons per Row', NULL, 'Ic&#244;nes par rang&#233;e'),
(397, 'Set the number of icons to display before beginning a new line.', NULL, 'D&#233;finir le nombre d''ic&#244;nes &#224; afficher avant de commencer une nouvelle ligne.'),
(398, 'Log Directory', NULL, 'ou r&#233;pertoire LOG'),
(399, 'Root path to directory log folders', NULL, 'Chemin de la racine vers les dossiers du LOG'),
(400, 'Mail method', NULL, 'Methode Mail'),
(401, 'Method to use when sending emails out. (mail = PHP Mail())', NULL, 'M&#233;thode &#224; utiliser lors de l''envoi de mails. (Mail = PHP mail ())'),
(402, 'Min Password Length', NULL, 'Longueur de mot de passe minimum'),
(403, 'Minimum length required for new passwords', NULL, 'Longueur minimale requise pour nouveau mot de passe'),
(404, 'Root Drive', NULL, 'R&#233;pertoire racine'),
(405, 'The root drive where ZPanel is installed.', NULL, 'R&#233;pertoire racine o&#249; est install&#233; ZPanel.'),
(406, 'Server IP Address', NULL, 'Adresse IP du serveur'),
(407, 'If set this will use this manually entered server IP address which is the prefered method for use behind a firewall.', NULL, 'Adresse recommand&#233;e pour utilisation derri&#232;re un pare-feu'),
(408, 'Service Check Timeout', NULL, 'V&#233;rifier le Temps d''activit&#233; du service'),
(409, 'SMTP Auth method', NULL, 'M&#233;thode d&#8217;authentification SMTP'),
(410, 'If specified will attempt to use encryption to connect to the server, if ''false'' this is disabled. Available options: false, ssl, tls', NULL, 'Si mentionn&#233;e, tentative de connexion crypt&#233;e.rnOptions disponibles: false, SSL, TLS'),
(411, 'SMTP Pass', NULL, 'Mot de passe SMTP'),
(412, 'Password for authentication on the SMTP server.', NULL, 'Mot de passe pour l''authentification sur le serveur SMTP.'),
(413, 'SMTP Port', NULL, 'Port SMTP'),
(414, 'The port address of the SMTP server (usually 25)', NULL, 'Port du serveur SMTP (Par d&#233;faut 25)'),
(415, 'SMTP Server', NULL, 'Serveur SMTP'),
(416, 'The address of the SMTP server.', NULL, 'L''adresse du serveur SMTP.'),
(417, 'SMTP User', NULL, 'Utilisateur SMTP'),
(418, 'Username for authentication on the SMTP server.', NULL, 'Nom d''utilisateur pour l''authentification sur le serveur SMTP.'),
(419, 'Temp Directory', NULL, 'R&#233;pertoire Temporaire'),
(420, 'Global temp directory.', NULL, 'R&#233;pertoire temporaire g&#233;n&#233;ral.'),
(421, 'Use AUTH', NULL, 'Utiliser l''authentification'),
(422, 'SMTP requires authentication. (true/false)', NULL, 'SMTP requiert une authentification.'),
(423, 'Use SMTP', NULL, 'Utiliser SMTP'),
(424, 'Use SMTP server to send emails from. (true/false)', NULL, 'Utiliser un serveur SMTP pour envoyer des emails.'),
(425, 'ZIP Exe', NULL, 'Executable ZIP'),
(426, 'Path to the ZIP Executable', NULL, 'Chemin de l''ex&#233;cutable ZIP'),
(427, 'ZPanel Debug Mode', NULL, 'Chemin du deboguage Panel'),
(428, 'Whether or not to show PHP debug errors,warnings and notices', NULL, 'Ne JAMAIS montrer les erreurs PHP, les avertissements et les messages d''erreurs !'),
(429, 'ZPanel Log file', NULL, 'Le fichier LOG ZPanel'),
(430, 'If loggging is set to ''file'' mode this is the path to the log file that is to be used by ZPanel.', NULL, 'Si loggging est r&#233;gl&#233; sur le mode "fichier", c''est le chemin vers le fichier LOG qui doit &#234;tre utilis&#233;.'),
(431, 'ZPanel root path', NULL, 'Chemin d''acc&#232;s racine ZPanel'),
(432, 'Zpanel Web Root', NULL, 'Fichiers "site" Zpanel'),
(433, 'zsudo path', NULL, 'chemin zsudo'),
(434, 'Path to the zsudo binary used by Apache to run system commands.', NULL, 'Chemin vers le binaire zsudo utilis&#233; par Apache pour ex&#233;cuter des commandes syst&#232;me.'),
(435, 'Current Cron Tasks', NULL, 'T&#226;ches Cron actuelles'),
(436, 'You currently do no have any tasks setup.', NULL, 'Aucune t&#226;che Cron.'),
(437, 'Script', NULL, 'Script'),
(438, 'example', NULL, 'Exemple'),
(439, 'Comment', NULL, 'Commentaire'),
(440, 'Executed', NULL, 'Ex&#233;cut&#233;'),
(441, 'Every 1 minute', NULL, 'Chaque minute'),
(442, 'Every 5 minutes', NULL, 'Toutes les 5 minutes'),
(443, 'Every 10 minutes', NULL, 'Toutes les 10 minutes'),
(444, 'Every 30 minutes', NULL, 'Toutes les 30 minutes'),
(445, 'Every 1 hour', NULL, 'Chaque 1 heure'),
(446, 'Every 2 hours', NULL, 'Toutes les 2 heures'),
(447, 'Every 8 hours', NULL, 'Toutes les 8 heures'),
(448, 'Every 12 hours', NULL, 'Toutes les 12 heures'),
(449, 'Every 1 day', NULL, 'Chaque jour 1'),
(450, 'Every week', NULL, 'Chaque semaine'),
(451, 'Select Folder', NULL, 'S&#233;lectionner un dossier'),
(452, 'root', NULL, 'racine'),
(453, 'Selected folder', NULL, 'Dossier s&#233;lectionn&#233;'),
(454, 'REMOVE Protection from Directory', NULL, 'Suppression de la protection du r&#233;pertoire'),
(455, 'Please confirm that you want to remove password protection from this directory.', NULL, 'Confirmer la suppression de la protection de ce r&#233;pertoire.'),
(456, 'EDIT .htaccess Users in Directory', NULL, 'G&#233;rer les utilisateurs de ce r&#233;pertoire.'),
(457, 'From here you can add or remove users that are allowed to access this directory', NULL, 'Ajouter ou supprimer des utilisateurs ayant acc&#232;s &#224; ce r&#233;pertoire.'),
(458, 'User', NULL, 'Utilisateur'),
(459, 'Encrypted Password', NULL, 'Mot de passe crypt&#233;'),
(460, 'Remove', NULL, 'Supprimer'),
(461, 'Add New User', NULL, 'Ajouter un nouvel utilisateur'),
(462, 'Confirm PW', NULL, 'Confirmer PW'),
(463, '.htaccess file is missing. Delete this password entry and recreate it to fix this error.', NULL, 'Le fichier .htaccess est manquant. veuillez supprimer cette entr&#233;e, et la recr&#233;er pour corriger cette erreur.'),
(464, 'Message', NULL, 'Message'),
(465, 'Restricted Area', NULL, 'Restricted Area'),
(466, 'Password protect your directories', NULL, 'Mot de passe de protection du r&#233;pertoire'),
(467, 'To begin, first select the directory you want to protect.', NULL, 'Pour commencer, s&#233;lectionnez d''abord le r&#233;pertoire que vous voulez prot&#233;ger.'),
(468, 'Click the folder Links to expand the directory tree.', NULL, 'Cliquez sur les liens de dossier pour d&#233;velopper l''arborescence du r&#233;pertoire.'),
(469, 'Click on the Select Folder button to select the directory for protection.', NULL, 'Cliquez sur le bouton "S&#233;lectionner un dossier" pour s&#233;lectionner le r&#233;pertoire &#224; prot&#233;ger.'),
(470, 'All Protected Directories', NULL, 'Tous les r&#233;pertoires prot&#233;g&#233;s'),
(471, 'Edit allowed users, or remove protection from passworded directories.', NULL, 'Modifier les utilisateurs autoris&#233;s, ou supprimer la protection du r&#233;pertoire..'),
(472, 'Directory', NULL, 'Annuaire'),
(473, 'Checking status of services...', NULL, 'V&#233;rification de l''&#233;tat des services ...'),
(474, 'Uptime', NULL, 'Uptime'),
(475, 'Daemon Status', NULL, 'Statut Daemon'),
(476, 'To view Webalizer stats for a particular domain or subdomain use the drop-down menu to select the domain or sub-domain you want to view. Stats may take up to 24 hours before they are generated.', NULL, 'Pour voir les stats Webalizer pour un domaine particulier ou sous-domaine utilisez le menu d&#233;roulant pour s&#233;lectionner le domaine ou sous-domaine que vous souhaitez afficher. Statistiques peut prendre jusqu''&#224; 24 heures avant qu''ils ne soient g&#233;n&#233;r&#233;s.'),
(477, 'Select Domain', NULL, 'S&#233;lectionner un domaine'),
(478, 'Display', NULL, 'Afficher'),
(479, 'You currently do not have any domains configured.', NULL, 'Aucun domaine configur&#233;'),
(480, 'Create a new domain', NULL, 'Cr&#233;er un nouveau domaine'),
(481, 'Current Sub-domains', NULL, 'Sous-domaines actuel'),
(482, 'Sub-domain', NULL, 'Sous-domaine'),
(483, 'You currently do not have any Sub-domains configured. Create a Sub-domain using the form below.', NULL, 'Aucun sous-domaine configur&#233;.rnCr&#233;ez-en un ci-dessous.'),
(484, 'You have reached your Sub-domains limit!', NULL, 'Vous avez atteint votre limite de sous-domaines.'),
(485, 'Current parked domains', NULL, 'Domaines actuellement r&#233;serv&#233;s'),
(486, 'Date parked', NULL, 'Date de r&#233;servation'),
(487, 'You currently do not have any parked domains setup on your account. Create a parked domain using the form below.', NULL, 'Aucun domaine r&#233;serv&#233;.rnR&#233;servez-en un ci-dessous.'),
(488, 'You have reached your parked domains limit!', NULL, 'Vous avez atteint votre limite de r&#233;servation de domaines.'),
(489, 'Delete Alias', NULL, 'Supprimer Alias'),
(490, 'Please confirm that you want to delete this Alias.', NULL, 'Confirmer la suppression de cet alias'),
(491, 'Current Aliases', NULL, 'Alias &#8203;&#8203;actuels'),
(492, 'Address', NULL, 'Adresse'),
(493, 'Destination', NULL, 'Destination'),
(494, 'You currently do not have any aliases configured on this server.', NULL, 'Aucun alias configur&#233;'),
(495, 'Create a new Alias', NULL, 'Cr&#233;er un nouvel alias'),
(496, 'Alias Address', NULL, 'Adresse Alias'),
(497, 'Select a mailbox', NULL, 'S&#233;lectionnez une bo&#238;te mail'),
(498, 'Sorry, you have reached your mailbox forward quota limit!', NULL, 'Quota de boites mail atteint !'),
(499, 'Delete Distribution List', NULL, 'Supprimer la liste de distribution'),
(500, 'Please confirm that you want to delete this distribution list.', NULL, 'Confirmer la suppression de la liste de distribution'),
(501, 'Edit Distribution List', NULL, 'Modifier la liste de distribution'),
(502, 'Add New Address', NULL, 'Ajouter une nouvelle adresse'),
(503, 'Add Mailbox', NULL, 'Ajouter la bo&#238;te mail'),
(504, 'Current Distribution Lists', NULL, 'Listes de distribution actuelles'),
(505, 'You currently do not have any distribution lists setup.', NULL, 'Aucune liste de distribution configur&#233;e.'),
(506, 'Create a new Distribution List', NULL, 'Cr&#233;er une liste de distribution'),
(507, 'You have reached your Distribution List quota limit!', NULL, 'Vous avez atteint votre quota limite de listes de distribution!'),
(508, 'Delete Forwarder', NULL, 'Supprimer Porteur'),
(509, 'Please confirm that you want to delete this forwarder.', NULL, 'Confirmer la suppression de cette redirection'),
(510, 'Current Forwarders', NULL, 'Porteurs actuels'),
(511, 'Keep Message', NULL, 'Garder un message'),
(512, 'Sorry there are currently no mailbox forwards configured!', NULL, 'Aucune boite mail configur&#233;e'),
(513, 'Create a new forward', NULL, 'Cr&#233;er un nouveau porteur'),
(514, 'Keep original message', NULL, 'Garder le message d''origine'),
(515, 'Delete Mailbox', NULL, 'Supprimer la bo&#238;te mail'),
(516, 'Please confirm that you want to delete this mailbox.', NULL, 'Confirmer la suppression de cette boite mail'),
(517, 'Edit mailbox', NULL, 'Modifier cette boite mail'),
(518, 'Set Password', NULL, 'D&#233;finir mot de passe'),
(519, 'Current mailboxes', NULL, 'Bo&#238;tes mail actuelles'),
(520, 'Date created', NULL, 'Date de cr&#233;ation'),
(521, 'Sorry there are currently no mailboxes configured!', NULL, 'Aucune boite mail configur&#233;e'),
(522, 'Create a new mailbox', NULL, 'Cr&#233;er une bo&#238;te mail'),
(523, 'Sorry, you have reached your mailbox quota limit!', NULL, 'D&#233;sol&#233;, vous avez atteint votre quota limite de bo&#238;tes mail!'),
(524, 'zpanel-hosting.tk', NULL, 'http://habbheberg.fr.nf'),
(525, 'zpanel.tk', NULL, 'http://habbheberg.fr.nf'),
(526, 'This module enables you to set a notice banner that will appear when any of your clients access ZPanel. ', NULL, 'Ce module permet de choisir une banni&#232;re pour le Panel'),
(527, 'Client message', NULL, 'Message clients'),
(528, 'Notice message', NULL, 'Message de notification'),
(529, 'Hi {{fullname}},\r\rWe are pleased to inform you that your new hosting account is now active, you can now login to ZPanel using the following credentials:\r\rUsername: {{username}}\rPassword: {{password}}', NULL, 'Bonjour {{fullname}}, rnNous avons le plaisir de vous annoncer que votre compte d''h&#233;bergement est d&#233;sormais actif. rnVous pouvez d&#233;sormais vous connecter en utilisant les identifiants suivants: rnNom d''utilisateur: {{username}} rnMot de passe: {{password}}'),
(530, 'Please confirm that you want to delete this client.', NULL, 'Confirmer la suppression de ce client (action irr&#233;versible, supprime toutes ses donn&#233;es).'),
(531, 'WARNING! This will remove all files and services belonging to this client!', NULL, 'ATTENTION ! Ceci va supprimer tous les fichiers et services qui d&#233;pendent de ce client.'),
(532, 'Move clients and packages (if any exist) this user has to', NULL, 'D&#233;placer les clients et packs (si existants) du revendeur vers'),
(533, 'Edit existing client', NULL, '&#201;diter un client existant'),
(534, 'User group', NULL, 'Groupe d''utilisateurs'),
(535, 'Current Clients', NULL, 'Clients Actuels'),
(536, 'Clients', NULL, 'Clients'),
(537, 'You have no client accounts at this time. Create a client using the form below.', NULL, 'Aucun compte client.rnCr&#233;ez-en un ci-dessous.'),
(538, 'You must first create a Package with the Package Manager module before you can create a client.', NULL, 'Vous devez d''abord cr&#233;er un package avant de cr&#233;er un client.'),
(539, 'Disabled Clients', NULL, 'Clients d&#233;sactiv&#233;s'),
(540, 'Create new client account', NULL, 'Cr&#233;er un nouveau compte client'),
(541, 'Usergroup', NULL, 'Groupe d''utilisateurs'),
(542, 'Send welcome email?', NULL, 'Envoyez l''email de bienvenue ?'),
(543, 'Email Subject', NULL, 'Sujet de l''email'),
(544, 'Your ZPanel Account details', NULL, 'Vos identifiants ZPanel'),
(545, 'Email Body', NULL, 'Contenu de l''email'),
(546, 'Delete FTP account', NULL, 'Supprimer un compte FTP'),
(547, 'Please confirm that you want to delete this FTP account.', NULL, 'Confirmer la suppression de ce compte FTP'),
(548, 'Reset FTP Password for user', NULL, 'R&#233;initialiser le mot de passe FTP pour l''utilisateur'),
(549, 'Current FTP accounts', NULL, 'Comptes FTP actuels'),
(550, 'Account name', NULL, 'Nom du compte'),
(551, 'Permission', NULL, 'Permission'),
(552, 'You do not have any FTP Accounts setup. Create an FTP account using the form below.', NULL, 'Aucun compte FTP.rnCr&#233;ez-en un ci-dessous.'),
(553, 'Create a new FTP Account', NULL, 'Cr&#233;ez un nouveau compte FTP'),
(554, 'Access type', NULL, 'Type d''acc&#232;s'),
(555, 'Read-only', NULL, 'Lecture uniquement');
INSERT INTO `x_translations` (`tr_id_pk`, `tr_en_tx`, `tr_German_tx`, `tr_French_tx`) VALUES
(556, 'Write-only', NULL, '&#201;criture uniquement'),
(557, 'Full access', NULL, 'Acc&#232;s complet'),
(558, 'You have reached your FTP account limit!', NULL, 'Vous avez atteint votre limite de comptes FTP !'),
(559, 'FTP Client Login', NULL, 'Connexion au client FTP'),
(560, 'Please choose the FTP account you want to log in with...', NULL, 'Veuillez choisir le compte FTP sur lequel vous souhaitez vous authentifier.'),
(561, 'You have no FTP accounts at this time.', NULL, 'Aucun compte FTP.');
