USE `sentora_core` ;
DROP TABLE IF EXISTS `x_translations`;

CREATE TABLE `x_translations` (
  `tr_id_pk` int(11) NOT NULL AUTO_INCREMENT,
  `tr_en_tx` text,
  `tr_German_tx` text,
  PRIMARY KEY (`tr_id_pk`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=832 ;

--
-- Contenu de la table `x_translations`
--

INSERT INTO `x_translations` (`tr_id_pk`, `tr_en_tx`, `tr_German_tx`) VALUES
(1, 'Webmail is a convenient way for you to check your email accounts online without the need to configure an email client.', 'Webmail ist ein bequemer Weg fÃ¼r Sie, Ihre E-Mail-Konten online zu Ã¼berprÃ¼fen, ohne dass eine E-Mail-Client zu konfigurieren.'),
(2, 'Launch Webmail', 'Starten Sie WebMail'),
(3, 'PHPInfo provides you with information regarding the version of PHP running on this system as well as installed PHP extentsions and configuration details.', 'PHPInfo bietet Ihnen Informationen über die PHP-Version auf dem System, sowie PHP installiert extentsions und Konfigurationsmöglichkeiten.'),
(4, 'From here you can shadow any of your client''s accounts, this enables you to automatically login as the user which enables you to offer remote help by seeing what they see!', 'Von hier aus können alle Ihre Kunden-Accounts können Schatten, ermöglicht Ihnen dies automatisch, wenn der Benutzer mit dem Sie remote helfen zu sehen, was sie sehen, anbieten zu können login!'),
(5, 'My Account', 'Meine Konto'),
(6, 'Change Password', 'Kennwort ändern'),
(7, 'Shadowing', 'Schatten'),
(8, 'ZPanel Config', 'Config ZPanel'),
(9, 'ZPanel News', 'ZPanel Aktuelles'),
(10, 'Updates', 'Aktualisierung'),
(11, 'Report Bug', 'Fehler melden'),
(12, 'Account', 'Konto'),
(13, 'Module Admin', 'Modul Admin'),
(14, 'Backup', 'Sicherungskopie'),
(15, 'Network Tools', 'Netzwerk-Tools'),
(16, 'Service Status', 'Service Status'),
(17, 'PHPInfo', 'PHPInfo'),
(18, 'phpMyAdmin', 'phpMyAdmin'),
(19, 'Domains', 'Domains'),
(20, 'Sub Domains', 'Sub Domains'),
(21, 'Parked Domains', 'geparkte Domains'),
(22, 'Manage Clients', 'Verwalten Kunden'),
(23, 'Package Manager', 'Paket Manager'),
(24, 'Server', 'Server'),
(25, 'Database', 'Datenbank'),
(26, 'Advanced', 'Fortgeschritten'),
(27, 'Mail', 'Post'),
(28, 'Reseller', 'Wiederverkäufer'),
(29, 'Account Information', 'Account Informationen'),
(30, 'Server Admin', 'Server Admin'),
(31, 'Database Management', 'Datenbank Verwalten'),
(32, 'Domain Management', 'Verwalten von Domains'),
(33, 'Find out all the latest news and information from the ZPanel project.', 'Finden Sie heraus, alle Neuigkeiten und Informationen aus dem ZPanel Projekt.'),
(34, 'Check to see if there are any available updates to your version of the ZPanel software.', 'Prüfen Sie, ob es irgendwelche verfügbaren Aktualisierungen für Ihre Version des ZPanel Software.'),
(35, 'If you have found a bug with ZPanel you can report it here.', 'Did you mean: If you have found a bug with CPanel you can report it here.\r\nWenn Sie einen Fehler mit ZPanel gefunden haben, können Sie ihn hier melden.'),
(36, 'phpMyAdmin is a web based tool that enables you to manage your ZPanel MySQL databases via. the web.', 'phpMyAdmin ist ein webbasiertes Tool, das Sie zu Ihrem ZPanel MySQL-Datenbanken via verwalten können. im Internet.'),
(37, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.', 'Aktuelle persönlichen Daten, die Sie uns mit vorgesehen ist, bitten wir Sie, diese zu halten bis zu Datum, falls wir mit Ihnen Kontakt aufnehmen über Ihre Hosting-Paket erfordern.'),
(38, 'Webmail is a convenient way for you to check your email accounts online without the need to configure an email client.', 'Webmail ist ein bequemer Weg für Sie, Ihre E-Mail-Konten online zu überprüfen, ohne dass eine E-Mail-Client zu konfigurieren.'),
(39, 'Change your current control panel password.', 'Ändern Sie Ihre aktuelle Bedienfeld oder MySQL-Kennwort.'),
(40, 'The backup manager module enables you to backup your entire hosting account including all your MySQL&reg databases.', 'Der Backup-Manager-Modul ermöglicht es Ihnen, Ihre gesamte Hosting-Account inklusive aller Ihrer MySQL &reg Datenbank-Backup.'),
(41, 'You can use the tools below to diagnose issues or to simply test connectivity to other servers or sites around the globe.', 'Sie können die folgenden Tools verwenden, um Probleme zu diagnostizieren oder einfach testen Verbindung mit anderen Servern oder Websites rund um den Globus.'),
(42, 'Here you can check the current status of our services and see what services are up and running and which are down and not.', 'Hier können Sie den aktuellen Status unserer Dienstleistungen und sehen, welche Dienste vorhanden sind und laufen, und die nach unten und es nicht sind.'),
(43, 'This module enables you to add or configure domain web hosting on your account.', 'Dieses Modul ermöglicht es Ihnen, hinzuzufügen oder zu konfigurieren Domain Hosting auf Ihrem Konto.'),
(44, 'Domain parking refers to the registration of an Internet domain name without that domain being used to provide services such as e-mail or a website. If you have any domains that you are not using, then simply park them!', 'Domain-Parking bezieht sich auf die Registrierung von Internet Domain-Namen ohne diese Domäne verwendet, um Dienste wie E-Mail oder eine Webseite bereitzustellen. Wenn Sie alle Domains, die Sie nicht haben, dann einfach parken sie!'),
(45, 'This module enables you to add or configure domain web hosting on your account.', 'Dieses Modul ermöglicht es Ihnen, hinzuzufügen oder zu konfigurieren Domain Hosting auf Ihrem Konto.'),
(46, 'Administer or configure modules registered with module admin', 'Verwalten oder zu konfigurieren Module mit Modul admin registriert'),
(47, 'The account manager enables you to view, update and create client accounts.', 'Die Account-Manager ermöglicht es Ihnen, anzuzeigen, zu aktualisieren und erstellen Kundenkonten.'),
(48, 'Welcome to the Package Manager, using this module enables you to create and manage existing reseller packages on your ZPanel hosting account.', 'Willkommen auf der Paket-Manager, mit diesem Modul ermöglicht Ihnen die Erstellung und Verwaltung von bestehenden Reseller-Pakete auf Ihrem ZPanel Hosting-Account.'),
(49, 'Gives you access to your files with drag-and-drop, multiple file uploading, text editing, zip support.', 'Ermöglicht den Zugriff auf Ihre Dateien mit Drag-and-drop, multiple Datei-Upload, Textbearbeitung, zip unterstützen.'),
(50, 'Secure FTP Applet is a JAVA based FTP client component that runs within your web browser. It is designed to let non-technical users exchange data securely with an FTP server.', 'Secure FTP Applet ist eine Java-basierte FTP-Client-Komponente, die in Ihrem Web-Browser läuft. Es wurde entwickelt, um nicht-technische Anwender den Datenaustausch secureiy lassen mit einem FTP-Server.'),
(51, 'Full name', 'Vollständiger Name'),
(52, 'Email Address', 'E-Mail Adresse'),
(53, 'Phone Number', 'Telefonnummer'),
(54, 'Choose Language', 'Sprache wählen'),
(55, 'Postal Address', 'Postanschrift'),
(56, 'Postal Code', 'Postleitzahl'),
(57, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.', 'Aktuelle persönlichen Daten, die Sie uns mit vorgesehen ist, bitten wir Sie, diese zu halten bis zu Datum, falls wir mit Ihnen Kontakt aufnehmen über Ihre Hosting-Paket erfordern.'),
(58, 'Changes to your account settings have been saved successfully!', 'Änderungen an Ihrem Konto-Einstellungen wurden erfolgreich gespeichert!'),
(59, 'Update Account', 'Aktualisierung Konto'),
(60, 'Enter your account details', 'Geben Sie Ihre Kontodaten'),
(61, 'Home', NULL),
(62, 'File', NULL),
(63, 'FTP Accounts', NULL),
(64, 'Client Notice Manager', NULL),
(65, 'Manage Groups', NULL),
(66, 'Theme Manager', NULL),
(67, 'xBilling', NULL),
(68, 'Aliases', NULL),
(69, 'Distribution Lists', NULL),
(70, 'Forwards', NULL),
(71, 'Mailboxes', NULL),
(72, 'WebMail', NULL),
(73, 'Domain', NULL),
(74, 'DNS Manager', NULL),
(75, 'MySQL Database', NULL),
(76, 'MySQL Users', NULL),
(77, 'Cron Manager', NULL),
(78, 'FAQ\\\\\\''s', NULL),
(79, 'Protect Directories', NULL),
(80, 'Webalizer Stats', NULL),
(81, 'Admin', NULL),
(82, 'phpSysInfo', NULL),
(83, 'ZXTS', NULL),
(84, 'Usage Viewer', NULL),
(85, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.\n', NULL),
(86, 'Username', NULL),
(87, 'Package name', NULL),
(88, 'Account type', NULL),
(89, 'Last Logon', NULL),
(90, 'Disk Quota', NULL),
(91, 'Bandwidth Quota', NULL),
(92, 'Used', NULL),
(93, 'Max', NULL),
(94, 'Sub-domains', NULL),
(95, 'Email Accounts', NULL),
(96, 'Email Forwarders', NULL),
(97, 'MySQL&reg; databases', NULL),
(98, 'Your IP', NULL),
(99, 'Server IP', NULL),
(100, 'Server OS', NULL),
(101, 'Apache Version', NULL),
(102, 'PHP Version', NULL),
(103, 'MySQL Version', NULL),
(104, 'ZPanel Version', NULL),
(105, 'Server uptime', NULL),
(106, 'FAQ\\''s', NULL),
(107, 'ChangeZP(br)Password', NULL),
(108, 'MyZP(br)Account', NULL),
(109, 'The account usage screen enables you to see exactly what you are currently using on your hosting package.', NULL),
(110, 'UsageZP(br)Viewer', NULL),
(111, 'ModuleZP(br)Admin', NULL),
(112, 'PHPInfo provides you with information regarding the version of PHP running on this system as well as installed PHP extensions and configuration details.', NULL),
(113, 'phpSysInfo is a web-based server hardware monitoring tool which enables you to see detailed hardware statistics of your server.', NULL),
(114, 'From here you can shadow any of your client\\\\\\''s accounts, this enables you to automatically login as the user which enables you to offer remote help by seeing what they see!', NULL),
(115, 'Changes made here affect the entire ZPanel configuration, please double check everything before saving changes.', NULL),
(116, 'ZPanelZP(br)Config', NULL),
(117, 'ZPanelZP(br)News', NULL),
(118, 'Here you can manage your lanuages, install new lanuages from ZXTS, and add support for symbolic lanuages', NULL),
(119, 'Here you can configure PHP scripts to run automatically at different time intervals.', NULL),
(120, 'CronZP(br)Manager', NULL),
(121, 'Please find a list of the most common questions from users, if you are unable to find a solution to your problem below please then contact your hosting provider. Simply click on the FAQ below to view the solution.', NULL),
(122, 'This module enables you to configure .htaccess files and users to protect your web directories.', NULL),
(123, 'ProtectZP(br)Directories', NULL),
(124, 'ServiceZP(br)Status', NULL),
(125, 'You can view many statistics such as visitor infomation, bandwidth used, referal infomation and most viewed pages etc. Web stats are based on Domains and sub-domains so to view web stats for a particular domain or subdomain use the drop-down menu to select the domain or sub-domain you want to view web stats for.', NULL),
(126, 'WebalizerZP(br)Stats', NULL),
(127, 'MySQL&reg databases are used by many PHP applications such as forums and ecommerce systems, below you can manage and create MySQL&reg databases.', NULL),
(128, 'MySQLZP(br)Database', NULL),
(129, 'MySQL&reg Users allows you to add users and permissions to your MySQL&reg databases.', NULL),
(130, 'MySQLZP(br)Users', NULL),
(131, '', NULL),
(132, 'DNSZP(br)Manager', NULL),
(133, 'ParkedZP(br)Domains', NULL),
(134, 'SubZP(br)Domains', NULL),
(135, 'Using this module you have the ability to create alias mailboxes to existing accounts.', NULL),
(136, 'This module enables you to create and manage email distribution groups.', NULL),
(137, 'DistributionZP(br)Lists', NULL),
(138, 'Using this module you have the ability to create mail forwarders.', NULL),
(139, 'Using this module you have the ability to create IMAP and POP3 Mailboxes.', NULL),
(140, 'Enables resellers to set global notices for their clients.', NULL),
(141, 'ClientZP(br)NoticeZP(br)Manager', NULL),
(142, 'ManageZP(br)Clients', NULL),
(143, 'Manage user groups to enable greater control over module permission.', NULL),
(144, 'ManageZP(br)Groups', NULL),
(145, 'PackageZP(br)Manager', NULL),
(146, 'Enables the reseller to set themes configurations for their clients.', NULL),
(147, 'ThemeZP(br)Manager', NULL),
(148, 'This module empower ZPanel with the ability of billable clients.', NULL),
(149, 'File Management', NULL),
(150, 'Using this module you can create FTP accounts which will enable you and any other accounts you create to have the ability to upload and manage files on your hosting space.', NULL),
(151, 'FTPZP(br)Accounts', NULL),
(152, 'Change<br/>Password', NULL),
(153, 'My<br/>Account', NULL),
(154, 'Usage<br/>Viewer', NULL),
(155, 'Module<br/>Admin', NULL),
(156, 'From here you can shadow any of your client\\''s accounts, this enables you to automatically login as the user which enables you to offer remote help by seeing what they see!', NULL),
(157, 'ZPanel<br/>Config', NULL),
(158, 'ZPanel<br/>News', NULL),
(159, 'Cron<br/>Manager', NULL),
(160, 'Protect<br/>Directories', NULL),
(161, 'Service<br/>Status', NULL),
(162, 'Webalizer<br/>Stats', NULL),
(163, 'MySQL<br/>Database', NULL),
(164, 'MySQL<br/>Users', NULL),
(165, 'DNS<br/>Manager', NULL),
(166, 'Parked<br/>Domains', NULL),
(167, 'Sub<br/>Domains', NULL),
(168, 'Distribution<br/>Lists', NULL),
(169, 'Client<br/>Notice<br/>Manager', NULL),
(170, 'Manage<br/>Clients', NULL),
(171, 'Manage<br/>Groups', NULL),
(172, 'Package<br/>Manager', NULL),
(173, 'Theme<br/>Manager', NULL),
(174, 'FTP<br/>Accounts', NULL),
(175, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.\n', NULL),
(176, 'Enter your current and new password', NULL),
(177, 'Current password', NULL),
(178, 'New password', NULL),
(179, 'Confirm new password', NULL),
(180, 'Change', NULL),
(181, 'Current personal details that you have provided us with, We ask that you keep these upto date in case we require to contact you regarding your hosting package.\r\n', NULL),
(182, 'Disk Usage Total', NULL),
(183, 'Package Usage Total', NULL),
(184, 'Disk space', NULL),
(185, 'Bandwidth', NULL),
(186, 'MySQL&reg databases', NULL),
(187, 'Mail forwarders', NULL),
(188, 'Pie chart', NULL),
(189, 'Domain Usage', NULL),
(190, 'Sub-Domain Usage', NULL),
(191, 'Parked-Domain Usage', NULL),
(192, 'MySQL&reg Database Usage', NULL),
(193, 'FTP Usage', NULL),
(194, 'Mailbox Usage', NULL),
(195, 'Forwarders Usage', NULL),
(196, 'Distribution List Usage', NULL),
(197, 'Administration Modules', NULL),
(198, 'Apache Config', NULL),
(199, 'Backup Config', NULL),
(200, 'DNS Config', NULL),
(201, 'FTP Config', NULL),
(202, 'Mail Config', NULL),
(203, 'Configure Modules', NULL),
(204, 'Module', NULL),
(205, 'On', NULL),
(206, 'Off', NULL),
(207, 'Category', NULL),
(208, 'Up-to-date?', NULL),
(209, 'Enabled', NULL),
(210, 'Disabled', NULL),
(211, 'N/A (Module Admin)', NULL),
(212, 'Save changes', NULL),
(213, 'Module Information', NULL),
(214, 'Module name', NULL),
(215, 'Module description', NULL),
(216, 'Module developer', NULL),
(217, 'Module version', NULL),
(218, 'Latest Version', NULL),
(219, 'Module Type', NULL),
(220, 'Install a new module', NULL),
(221, 'You can automatically install a new module by uploading your zpanel package archive (.zpp file) and then click \\\\\\''Install\\\\\\'' to begin the process.', NULL),
(222, 'Install!', NULL),
(223, 'You can automatically install a new module by uploading your zpanel package archive (.zpp file) and then click \\''Install\\'' to begin the process.', NULL),
(224, 'This module enables you to configure Apache Vhost settings for your hosting accounts.', NULL),
(225, 'Configure your Apache Settings', NULL),
(226, 'Access Log Format', NULL),
(227, 'Log format for the Apache access log', NULL),
(228, 'Allow Disabled', NULL),
(229, 'Allow webhosts to remain active even if a user has been disabled.', NULL),
(230, 'Apache Binary', NULL),
(231, 'Path to the Apache binary', NULL),
(232, 'Apache Port', NULL),
(233, 'Apache service port', NULL),
(234, 'Apache Restart Cmd', NULL),
(235, 'Command line arguments used after the restart service request when reloading Apache.', NULL),
(236, 'Apache Service Name', NULL),
(237, 'Service name used to handle Apache service control', NULL),
(238, 'Apache VHOST Conf', NULL),
(239, 'The full system path and filename of the Apache VHOST configuration name.', NULL),
(240, 'Bandwidth Log Format', NULL),
(241, 'Log format for the Apache bandwidth log', NULL),
(242, 'Directory Indexes', NULL),
(243, 'Directory Index', NULL),
(244, 'Disable HOSTS file entries', NULL),
(245, 'Disable host entries', NULL),
(246, 'Global VHost Entry', NULL),
(247, 'Extra directives for all apache vhost\\''s.', NULL),
(248, 'Global ZPanel Entry', NULL),
(249, 'Extra directives for Zpanel default vhost.', NULL),
(250, 'Open Base Temp Directory', NULL),
(251, 'Temp directory used in open_base_directory setting', NULL),
(252, 'Purge Backups', NULL),
(253, 'Old backups are deleted after the date set in Puge Date', NULL),
(254, 'Purge Date', NULL),
(255, 'Time in days that vhost backups are safe from deletion', NULL),
(256, 'Shared Domains', NULL),
(257, 'Domains entered here can be shared across multiple accounts. Seperate domains with , example: no-ip,dyndns', NULL),
(258, 'Static Pages Directory', NULL),
(259, 'The ZPanel static directory, used for storing welcome pages etc. etc.', NULL),
(260, 'Suhosin Value', NULL),
(261, 'Suhosin configuration for virtual host  blacklisting commands', NULL),
(262, 'Upload Temp Directory', NULL),
(263, 'The path to the Apache Upload directory (with trailing slash)', NULL),
(264, 'Use Open Base Dir', NULL),
(265, 'Enable openbase directory for all vhosts', NULL),
(266, 'Use Suhosin', NULL),
(267, 'Enable Suhosin for all vhosts', NULL),
(268, 'VHost Backup', NULL),
(269, 'Backup vhost file before a new one is written', NULL),
(270, 'VHost Backup Dir', NULL),
(271, 'Directory that vhost.conf backups are stored.', NULL),
(272, 'Vhost Parking Path', NULL),
(273, 'The path to the parking website, this will be used by all clients.', NULL),
(274, 'Vhosts Directory', NULL),
(275, 'Virtual host directory', NULL),
(276, 'Force Update', NULL),
(277, 'Force vhost.conf to be updated on next daemon run. Any change in settings also triggers vhost.conf to be updated.', NULL),
(278, 'Cancel', NULL),
(279, 'Override a Virtual Host Setting', NULL),
(280, 'Select Vhost', NULL),
(281, 'Select a domain', NULL),
(282, 'All Virtual Hosts with Overrides', NULL),
(283, 'Disabled Virtual Hosts', NULL),
(284, 'Delete', NULL),
(285, 'Please confirm that you want to delete this domain.', NULL),
(286, 'Current domains', NULL),
(287, 'Domain name', NULL),
(288, 'Home directory', NULL),
(289, 'Status', NULL),
(290, 'You currently do not have any domains configured. Create a domain using the form below.', NULL),
(291, 'Create a new home directory', NULL),
(292, 'Use existing home directory', NULL),
(293, 'You have reached your domain limit!', NULL),
(294, 'Changes to your domain web hosting has been saved successfully.', NULL),
(295, 'Pending', NULL),
(296, 'Your domain will become active at the next scheduled update.  This can take up to one hour.', NULL),
(297, 'Live', NULL),
(298, 'Virtual Host Override', NULL),
(299, 'Set options for virtual host', NULL),
(300, 'Domain Enabled', NULL),
(301, 'Suhosin Enabled', NULL),
(302, 'OpenBase Enabled', NULL),
(304, 'Port Override', NULL),
(305, 'Forward Port 80 to Overriden Port', NULL),
(306, 'Warning requires Apache mod_rewrite to be installed on the server.', NULL),
(307, 'IP Override', NULL),
(308, 'Custom Entry', NULL),
(309, 'Save Vhost', NULL),
(310, 'Changes to your settings have been saved successfully!', NULL),
(311, 'This module enables you to configure Backup settings for your hosting accounts.', NULL),
(312, 'Configure your Backup Settings', NULL),
(313, 'Daily Backups', NULL),
(314, 'Make a daily backup of each clients data, including MySQL databases to their backup folder. Backups will still be created if Disk Backups are set to false. (true/false)', NULL),
(315, 'Disk Backups', NULL),
(316, 'Allow users to create and save backups of their home directories to disk. (true/false)', NULL),
(317, 'Delete client backups after allotted time has elapsed to help save diskspace (true/false)', NULL),
(318, 'Time in days backups are safe from being deleted. After days have elapsed, older backups will be deleted on Daemon Day Run', NULL),
(319, 'This module enables you to configure DNS settings for the DNS Manager', NULL),
(320, 'Configure your DNS Settings', NULL),
(321, 'General', NULL),
(322, 'Tools', NULL),
(323, 'Services', NULL),
(324, 'Logs', NULL),
(325, 'Allow Custom IP', NULL),
(326, 'Allow users to change IP settings in A records. If set to false, IP is locked to server IP setting in ZPanel Config', NULL),
(327, 'Allow Zone Transfers', NULL),
(328, 'Setting to restrict zone transfers in setting: allow-transfer {}; Default = all', NULL),
(329, 'Allowed Record Types', NULL),
(330, 'Types of records allowed seperated by a space. Default = A AAAA CNAME MX TXT SRV SPF NS', NULL),
(331, 'Bind Log', NULL),
(332, 'Path and name of the Bind Log', NULL),
(333, 'BIND Service Name', NULL),
(334, 'Name of the BIND service', NULL),
(335, 'Named CheckConfig', NULL),
(336, 'Path to named-checkconf bind utility.', NULL),
(337, 'Named CheckZone', NULL),
(338, 'Path to named-checkzone bind utility.', NULL),
(339, 'Named CompileZone', NULL),
(340, '	Path to named-compilezone bind utility.', NULL),
(341, 'Named Config', NULL),
(342, 'Named configuration file', NULL),
(343, 'Named Directory', NULL),
(344, 'Path to the directory where named.conf is stored', NULL),
(345, 'Path to BIND Root', NULL),
(346, 'Path to the root directory where BIND is installed.', NULL),
(347, 'SOA Expire TTL', NULL),
(348, 'Global expire TTL. Default = 604800 (1 week)', NULL),
(349, 'SOA Minimum TTL', NULL),
(350, 'Global minimum TTL. Default = 86400 (1 day)', NULL),
(351, 'SOA Refesh TTL', NULL),
(352, 'Global refresh TTL.  Default = 21600 (6 hours)', NULL),
(353, 'SOA Retry TTL', NULL),
(354, 'Global retry TTL. Default = 3600 (1 hour)', NULL),
(355, 'Zone Directory', NULL),
(356, 'Path to where DNS zone files are stored', NULL),
(357, 'Reset all Records to Default', NULL),
(358, 'GO', NULL),
(359, 'Reset Records to Default on Single Domain', NULL),
(360, 'Select Domain', NULL),
(361, 'Add Default Records to Missing Domains', NULL),
(362, 'Delete Record Type from ALL Records', NULL),
(364, 'Purge Deleted Zone Records From Database', NULL),
(365, 'Delete ALL Zone Records', NULL),
(366, 'Force Records Update on Next Daemon Run', NULL),
(367, 'Start Service', NULL),
(368, 'Stop Service', NULL),
(369, 'Reload BIND', NULL),
(370, 'Service Port Status', NULL),
(371, 'RUNNING', NULL),
(372, 'Log file is not Readable', NULL),
(373, 'Set Permissions', NULL),
(374, 'Clear errors', NULL),
(375, 'Clear', NULL),
(376, 'Clear warnings', NULL),
(377, 'Clear logs', NULL),
(378, 'View Errors', NULL),
(379, 'View', NULL),
(380, 'View warnings', NULL),
(381, 'View logs', NULL),
(382, 'STOPPED', NULL),
(383, 'No permission to write to log file.', NULL),
(384, 'Path to named-compilezone bind utility.', NULL),
(385, 'This module enables you to configure FTP settings for your hosting accounts.', NULL),
(386, 'Configure your FTP Settings', NULL),
(387, 'FTP Config File', NULL),
(388, 'The path to the configuration file if applicable.', NULL),
(389, 'FTP Database', NULL),
(390, 'The name of the ftp server database', NULL),
(391, 'FTP PHP', NULL),
(392, 'Name of PHP to include when adding FTP data.', NULL),
(393, 'FTP Service Name', NULL),
(394, 'The name of the FTP service', NULL),
(395, 'FTP Service Root', NULL),
(396, 'The path to the service executable if applicable.', NULL),
(397, 'This module enables you to configure your mail options', NULL),
(398, 'Configure your Mail Settings', NULL),
(399, 'Mailserver Database', NULL),
(400, 'The name of the mail server database', NULL),
(401, 'Mailserver PHP', NULL),
(402, 'Name of PHP to include when adding mailbox data.', NULL),
(403, 'Max Mailbox Size', NULL),
(404, 'Maximum size in megabytes allowed for mailboxes. Default = 200', NULL),
(405, 'Remove Orphans', NULL),
(406, 'When domains are deleted, also delete all mailboxes for that domain when the daemon runs. (true/false)', NULL),
(407, 'View full PHP configuration', NULL),
(408, 'Select the client you wish to shadow', NULL),
(409, 'Package', NULL),
(410, 'Group', NULL),
(411, 'Current Disk', NULL),
(412, 'Current Bandwidth', NULL),
(413, 'Shadow', NULL),
(414, 'You have no Clients at this time.', NULL),
(415, 'Hi {{fullname}},\n\nWe are pleased to inform you that your new hosting account is now active!\n\nYou can access your web hosting control panel using this link:\n{{controlpanelurl}}\n\nYour username and password is as follows:\nUsername: {{username}}\nPassword: {{password}}\n\nMany thanks,\nThe management', NULL),
(416, 'Please confirm that you want to delete this client.', NULL),
(417, 'WARNING! This will remove all files and services belonging to this client!', NULL),
(418, 'Move clients and packages (if any exist) this user has to', NULL),
(419, 'Edit existing client', NULL),
(420, 'Reset password', NULL),
(421, 'Save', NULL),
(422, 'Current Clients', NULL),
(423, 'Clients', NULL),
(424, 'You have no client accounts at this time. Create a client using the form below.', NULL),
(425, 'You must first create a Package with the Package Manager module before you can create a client.', NULL),
(426, 'Disabled Clients', NULL),
(427, 'Create new client account', NULL),
(428, 'Password', NULL),
(429, 'Generate Password', NULL),
(430, 'Send welcome email', NULL),
(431, 'Email subject', NULL),
(432, 'Your ZPanel Account details', NULL),
(433, 'Email body', NULL),
(434, 'Administrators', NULL),
(435, 'Resellers', NULL),
(436, 'Users', NULL),
(437, 'Administration', NULL),
(438, 'Demo', NULL),
(439, 'Changes to your client(s) have been saved successfully!', NULL),
(440, 'Another user account is already using this email address.', NULL),
(441, 'Hi {{fullname}},\r\rWe are pleased to inform you that your new hosting account is now active!\r\rYou can access your web hosting control panel using this link:\r{{controlpanelurl}}\r\rYour username and password is as follows:\rUsername: {{username}}\rPassword: {{password}}\r\rMany thanks,\rThe management', NULL),
(442, 'Configure your ZPanel Settings', NULL),
(443, 'ZPanel Daemon', NULL),
(444, 'Next Daemon Run', NULL),
(445, 'Never', NULL),
(446, 'Last Daemon Run', NULL),
(447, 'Last Day Daemon Run', NULL),
(448, 'Last Week Daemon Run', NULL),
(449, 'Last Month Daemon Run', NULL),
(450, 'Queue a full daemon run (reset)', NULL),
(451, 'Run Daemon Now', NULL),
(452, 'Date Format', NULL),
(453, 'Set the date format used by modules.', NULL),
(454, 'Debug logging mode', NULL),
(455, 'The default mode to log all errors in.', NULL),
(456, 'From Address', NULL),
(457, 'The email address to appear in the From field of emails sent by ZPanel.', NULL),
(458, 'From Name', NULL),
(459, 'The name to appear in the From field of emails sent by ZPanel.', NULL),
(460, 'Icons per Row', NULL),
(461, 'Set the number of icons to display before beginning a new line.', NULL),
(462, 'Log Directory', NULL),
(463, 'Root path to directory log folders', NULL),
(464, 'Mail method', NULL),
(465, 'Method to use when sending emails out. (mail = PHP Mail())', NULL),
(466, 'Min Password Length', NULL),
(467, 'Minimum length required for new passwords', NULL),
(468, 'Remote Login Forms', NULL),
(469, 'Disables CSFR protection on the login form to enable remote login forms.', NULL),
(470, 'Root Drive', NULL),
(471, 'The root drive where ZPanel is installed.', NULL),
(472, 'Server IP Address', NULL),
(473, 'If set this will use this manually entered server IP address which is the prefered method for use behind a firewall.', NULL),
(474, 'Service Check Timeout', NULL),
(475, 'SMTP Auth method', NULL),
(476, 'If specified will attempt to use encryption to connect to the server, if \\''false\\'' this is disabled. Available options: false, ssl, tls', NULL),
(477, 'SMTP Pass', NULL),
(478, 'Password for authentication on the SMTP server.', NULL),
(479, 'SMTP Port', NULL),
(480, 'The port address of the SMTP server (usually 25)', NULL),
(481, 'SMTP Server', NULL),
(482, 'The address of the SMTP server.', NULL),
(483, 'SMTP User', NULL),
(484, 'Username for authentication on the SMTP server.', NULL),
(485, 'Temp Directory', NULL),
(486, 'Global temp directory.', NULL),
(487, 'Use AUTH', NULL),
(488, 'SMTP requires authentication. (true/false)', NULL),
(489, 'Use SMTP', NULL),
(490, 'Use SMTP server to send emails from. (true/false)', NULL),
(491, 'ZIP Exe', NULL),
(492, 'Path to the ZIP Executable', NULL),
(493, 'ZPanel Debug Mode', NULL),
(494, 'Whether or not to show PHP debug errors,warnings and notices', NULL),
(495, 'ZPanel Log file', NULL),
(496, 'If logging is set to \\''file\\'' mode this is the path to the log file that is to be used by ZPanel.', NULL),
(497, 'ZPanel root path', NULL),
(498, 'Zpanel Web Root', NULL),
(499, 'zsudo path', NULL),
(500, 'Path to the zsudo binary used by Apache to run system commands.', NULL),
(501, 'Latest Zpanel News', NULL),
(502, 'Click to view this news item', NULL),
(503, 'Backup your hosting account files', NULL),
(504, 'Launch', NULL),
(505, 'Backups your data whilst you wait and then prompt\\\\\\''s you to download the backup archive.', NULL),
(506, 'There are no files in your public folder to back up.', NULL),
(507, 'Backup Archives', NULL),
(508, 'Archived files will automatically be deleted when they are older than', NULL),
(509, 'days', NULL),
(510, 'Refresh archive list', NULL),
(511, 'Location', NULL),
(512, 'File Size', NULL),
(513, 'DELETE BACKUP', NULL),
(514, 'You have no backups at this time.  If you have just created a backup then try refreshing', NULL),
(515, 'Backup to disk is not enabled on the server. You may still download backups directly to your computer through your browser.', NULL),
(516, 'Backups your data whilst you wait and then prompt\\''s you to download the backup archive.', NULL),
(517, 'Current Cron Tasks', NULL),
(518, 'You currently do not have any tasks setup.', NULL),
(519, 'Script', NULL),
(520, 'example', NULL),
(521, 'Comment', NULL),
(522, 'Executed', NULL),
(523, 'Every 1 minute', NULL),
(524, 'Every 5 minutes', NULL),
(525, 'Every 10 minutes', NULL),
(526, 'Every 30 minutes', NULL),
(527, 'Every 1 hour', NULL),
(528, 'Every 2 hours', NULL),
(529, 'Every 8 hours', NULL),
(530, 'Every 12 hours', NULL),
(531, 'Every 1 day', NULL),
(532, 'Every week', NULL),
(533, 'Every month', NULL),
(534, 'Create', NULL),
(535, 'Delete FAQ Item', NULL),
(536, 'Please confirm that you want to delete this FAQ item.', NULL),
(537, 'Frequently Asked Questions', NULL),
(538, 'Add FAQ Item', NULL),
(539, 'Since you are logged in as an Administrator or a Reseller, you can add and remove FAQ items.  Administrators can see and remove all FAQ items, but Resellers can only remove FAQ items they have created.  Your clients will be able to see any FAQ items you create, plus any FAQ items created by an Administrator. Your clients will not be able to add or remove any FAQ items.', NULL),
(540, 'Add', NULL),
(541, 'Checking status of services...', NULL),
(542, 'Uptime', NULL),
(543, 'Daemon Status', NULL),
(544, 'To view Webalizer stats for a particular domain or subdomain use the drop-down menu to select the domain or sub-domain you want to view. Stats may take up to 24 hours before they are generated.', NULL),
(545, 'Display', NULL),
(546, 'You currently do not have any domains configured.', NULL),
(547, 'Create a new domain', NULL),
(548, 'Delete database', NULL),
(549, 'Please confirm that you want to delete this database.', NULL),
(550, 'Current MySQL&reg Databases', NULL),
(551, 'Database name', NULL),
(552, 'Size', NULL),
(553, 'You have no databases at this time. Create a database using the form below.', NULL),
(554, 'Create a new MySQL&reg database', NULL),
(555, 'You have reached your MySQL database limit!', NULL),
(556, 'Delete User', NULL),
(557, 'Please confirm that you want to delete this MySQL user.', NULL),
(558, 'Databases for user', NULL),
(559, 'Remove from user', NULL),
(560, 'Remove database', NULL),
(561, 'This user currently has no databases. Assign a database using the form below.', NULL),
(562, 'Add Database', NULL),
(563, 'Save Password', NULL),
(564, 'Current MySQL&reg Users', NULL),
(565, 'User name', NULL),
(566, 'Access', NULL),
(567, 'Databases', NULL),
(568, 'Edit', NULL),
(569, 'You have no MySQL&reg users at this time. Create a user using the form below.', NULL),
(570, 'Create a new MySQL&reg User', NULL),
(571, 'Map Database', NULL),
(572, 'Remote Access', NULL),
(573, 'Allow from any IP', NULL),
(574, 'Only from single IP', NULL),
(575, 'Launch phpMyAdmin', NULL),
(576, 'Manage Domains', NULL),
(577, 'Choose fom the list of domains below', NULL),
(578, 'Create Default DNS Records', NULL),
(579, 'No records were found for this domain.  Click the button below to set up your domain records for the first time', NULL),
(580, 'Create Records', NULL),
(581, 'Your DNS zone has been loaded without errors.', NULL),
(582, 'DNS records for', NULL),
(583, 'Undo Changes', NULL),
(584, 'Domain List', NULL),
(585, 'The A record contains an IPv4 address. It\\''s target is an IPv4 address, e.g. \\''192.168.1.1\\''.', NULL),
(586, 'The AAAA record contains an IPv6 address. It\\''s target is an IPv6 address, e.g. \\''2607:fe90:2::1\\''.', NULL),
(587, 'The CNAME record specifies the canonical name of a record. It\\''s target is a fully qualified domain name, e.g.\n\\''webserver-01.example.com\\''.', NULL),
(588, 'The MX record specifies a mail exchanger host for a domain. Each mail exchanger has a priority or preference that is a numeric value between 0 and 65535.  It\\''s target is a fully qualified domain name, e.g. \\''mail.example.com\\''.', NULL),
(589, 'The TXT field can be used to attach textual data to a domain.', NULL),
(590, 'SRV records can be used to encode the location and port of services on a domain name.  It\\''s target is a fully qualified domain name, e.g. \\''host.example.com\\''.', NULL),
(591, 'SPF records is used to store Sender Policy Framework details.  It\\''s target is a text string, e.g.<br>\\''v=spf1 a:192.168.1.1 include:example.com mx ptr -all\\'' (Click <a href=\\"http://www.microsoft.com/mscorp/safety/content/technologies/senderid/wizard/\\" target=\\"_blank\\">HERE</a> for the Microsoft SPF Wizard.)', NULL),
(592, 'Nameserver record. Specifies nameservers for a domain. It\\''s target is a fully qualified domain name, e.g.  \\''ns1.example.com\\''.  The records should match what the domain name has registered with the internet root servers.', NULL),
(593, 'Host Name', NULL),
(594, 'Target', NULL),
(595, 'Actions', NULL),
(596, 'Add New Record', NULL),
(597, 'TTL', NULL),
(598, 'Priority', NULL),
(599, 'Weight', NULL),
(600, 'Port', NULL),
(601, 'Please note that changes to your zone records can take up to 24 hours before they become \\''live\\''.', NULL),
(602, 'Output of DNS zone checker:', NULL),
(603, 'Current Sub-domains', NULL),
(604, 'Sub-domain', NULL),
(605, 'You currently do not have any Sub-domains configured. Create a Sub-domain using the form below.', NULL),
(606, 'You have reached your Sub-domains limit!', NULL),
(607, 'Delete Alias', NULL),
(608, 'Please confirm that you want to delete this Alias.', NULL),
(609, 'Current Aliases', NULL),
(610, 'Address', NULL),
(611, 'Destination', NULL),
(612, 'You currently do not have any aliases configured on this server.', NULL),
(613, 'Create a new Alias', NULL),
(614, 'Alias Address', NULL),
(615, 'Select a mailbox', NULL),
(616, 'Sorry, you have reached your mailbox forward quota limit!', NULL),
(617, 'Delete Distribution List', NULL),
(618, 'Please confirm that you want to delete this distribution list.', NULL),
(619, 'Edit Distribution List', NULL),
(620, 'Add New Address', NULL),
(621, 'Add Mailbox', NULL),
(622, 'Current Distribution Lists', NULL),
(623, 'You currently do not have any distribution lists setup.', NULL),
(624, 'Create a new Distribution List', NULL),
(625, 'You have reached your Distribution List quota limit!', NULL),
(626, 'Delete Forwarder', NULL),
(627, 'Please confirm that you want to delete this forwarder.', NULL),
(628, 'Current Forwarders', NULL),
(629, 'Keep Message', NULL),
(630, 'Sorry there are currently no mailbox forwards configured!', NULL),
(631, 'Create a new forward', NULL),
(632, 'Keep original message', NULL),
(633, 'Delete Mailbox', NULL),
(634, 'Please confirm that you want to delete this mailbox.', NULL),
(635, 'Edit mailbox', NULL),
(636, 'Set Password', NULL),
(637, 'Current mailboxes', NULL),
(638, 'Date created', NULL),
(639, 'Sorry there are currently no mailboxes configured!', NULL),
(640, 'Create a new mailbox', NULL),
(641, 'Sorry, you have reached your mailbox quota limit!', NULL),
(642, 'This module enables you to set a notice banner that will appear when any of your clients access ZPanel. ', NULL),
(643, 'Client message', NULL),
(644, 'Notice message', NULL),
(645, 'This module enables you to manage user groups for your client, User groups enable you to control what modules your users can see and access. ', NULL),
(646, 'Delete user group', NULL),
(647, 'Please confirm and choose a group to move any existing clients to before the selected group is deleted.', NULL),
(648, 'Please confirm that you want to delete this group.', NULL),
(649, 'Move current group members to', NULL),
(650, 'Default user groups', NULL),
(651, 'Description ', NULL),
(652, 'Current user groups', NULL),
(653, 'There are currently no custom user groups configured!', NULL),
(654, 'Create new user group', NULL),
(655, 'Group name', NULL),
(656, 'Edit user group', NULL),
(657, 'The main administration group, this group allows access to all areas of ZPanel.', NULL),
(658, 'Resellers have the ability to manage, create and maintain user accounts within ZPanel.', NULL),
(659, 'Users have basic access to ZPanel.', NULL),
(660, 'Delete package', NULL),
(661, 'Please confirm and choose a package to move any existing clients to before the selected package is deleted.', NULL),
(662, 'Package to delete', NULL),
(663, 'Move current package members to', NULL),
(664, 'Edit package', NULL),
(665, 'Enable PHP', NULL),
(666, 'Enable CGI', NULL),
(667, 'No. Domains', NULL),
(668, 'No. Sub-domains', NULL),
(669, 'No. Parked domains', NULL),
(670, 'No. Mailboxes', NULL),
(671, 'No. Forwarders', NULL),
(672, 'No. Dist Lists', NULL),
(673, 'No. FTP accounts', NULL),
(674, 'No. MySQL databases', NULL),
(675, 'Disk space quota', NULL),
(676, 'Monthly bandwidth quota', NULL),
(677, 'Created', NULL),
(678, 'No. of clients', NULL),
(679, 'You have no packages at this time. Create a package using the form below.', NULL),
(680, 'Create a new package', NULL),
(681, 'As a reseller you can configure theme settings for your clients. If the theme you select has multiple CSS versions you will be prompted for which theme \\\\\\''version\\\\\\'' you would like to use after you \\\\\\''save\\\\\\'' the changes.', NULL),
(682, 'Select a theme', NULL),
(683, 'Theme name', NULL),
(684, 'Theme variation', NULL),
(685, 'Update', NULL),
(686, 'As a reseller you can configure theme settings for your clients. If the theme you select has multiple CSS versions you will be prompted for which theme \\''version\\'' you would like to use after you \\''save\\'' the changes.', NULL),
(687, 'Delete FTP account', NULL),
(688, 'Please confirm that you want to delete this FTP account.', NULL),
(689, 'Reset FTP Password for user', NULL),
(690, 'Current FTP accounts', NULL),
(691, 'Account name', NULL),
(692, 'Permission', NULL),
(693, 'You do not have any FTP Accounts setup. Create an FTP account using the form below.', NULL),
(694, 'Create a new FTP Account', NULL),
(695, 'Access type', NULL),
(696, 'Read-only', NULL),
(697, 'Write-only', NULL),
(698, 'Full access', NULL),
(699, 'Set Master home directory', NULL),
(700, 'Use Domain directory', NULL),
(701, 'You have reached your FTP account limit!', NULL),
(702, 'Repo Browser', NULL),
(703, 'Changes to your module options have been saved successfully!', NULL),
(704, 'Repo Browser allows you to manage your custom module repositories.', NULL),
(705, 'RepoZP(br)Browser', NULL),
(706, 'Repo<br/>Browser', NULL),
(707, 'ZPPY Patch Needed', NULL),
(708, 'For ZPanel versions BELOW 10.1.0 Repo Browser can not uninstall a module until your zppy file is patched. Your original file will be saved so you can revert back at a later time if you wish.', NULL),
(709, 'Press the PATCH button to install the modded zppy file and try uninstalling the module again.', NULL),
(710, 'Patch', NULL),
(711, 'Remove Repository', NULL),
(712, 'Please confirm that you want to remove this repository from your ZPanel server.', NULL),
(713, 'Remove', NULL),
(714, 'Debug ZPPY Client output', NULL),
(715, 'Validation failed for repository', NULL),
(716, 'The repository you are trying to add does not appear to be a valid ZPanel repository, or the repository may be offline. You can choose to ignore this and add the repository anyway. ', NULL),
(717, 'Add Anyway', NULL),
(718, 'Remove Module', NULL),
(719, 'Please confirm that you want to remove this module from your ZPanel server.', NULL),
(720, 'Install Module', NULL),
(721, 'Please confirm that you want to install this module on your ZPanel server.', NULL),
(722, 'Install', NULL),
(723, 'Update Module Database Version Number', NULL),
(724, 'You are about to manually update the version number that ZPanel is reporting with the version number that is actually reported by your module file.', NULL),
(725, 'ZPanel database version', NULL),
(726, 'Will be set to version', NULL),
(727, 'Update Module', NULL),
(728, 'Available Modules', NULL),
(729, 'total modules', NULL),
(730, 'No modules available for download.', NULL),
(731, 'Repositories', NULL),
(732, 'You currently do not have any repositories configured.', NULL),
(733, 'ZPPY Client', NULL),
(734, 'Manually run a ZPPY client command.', NULL),
(735, 'Run Command', NULL),
(736, 'Module Developer Notes', NULL),
(737, 'Command Given', NULL),
(738, 'Command Response', NULL),
(739, 'Repository and ZPPY cache has been updated successfully.', NULL),
(740, 'ZPPY COMMAND OUTPUT', NULL),
(741, 'Apache Status', NULL),
(742, 'Apache Status makes the Apache server status readable, sortable and searchable to identify and troubleshoot Apache performance issues or individual websites.', NULL),
(743, 'ApacheZP(br)Status', NULL),
(744, 'Apache<br/>Status', NULL),
(745, 'ZPanel localhost server status', NULL),
(746, 'Extended Status Needs to be ON', NULL),
(747, 'Mod_Status Needs to be enabled', NULL),
(748, 'Here you can manage your lanuages, install new lanuages from ZXTS, and add support for symbolic lanuages.', NULL),
(749, 'Apply Symbolic Language Support', NULL),
(750, 'Explanation', NULL),
(751, 'In ZPanelX there are a few tasks that need to be undertook for ZPanelX to support symbolic lanuages. The below will handle all the task for you.', NULL),
(752, 'Have Problems?', NULL),
(753, 'In an event that you update ZPanelX and the symbolic lanuages stop showing correctly just click Apply Symbolic Support button below and the languages should start to show properly again.', NULL),
(754, 'If the lanaguages still do not show up properly then clikc the install button on the lanuage again', NULL),
(755, 'If you have installed an symbolic lanuage before appling the patch please first apply the patch by click Apply Symbolic Support button and then click the install button on the lanuage again.', NULL),
(756, 'Symbolic Language Support Applied?', NULL),
(757, 'Symbolic Language Support is <strong>NOT</strong> currently applied', NULL),
(758, 'Apply Symbolic Language Support: ', NULL),
(759, 'Apply Symbolic Support', NULL),
(760, 'Remove Symbolic Language Support: ', NULL),
(761, 'Remove Symbolic Support', NULL),
(762, 'Install or Update', NULL),
(763, 'Un-Install Lanuage', NULL),
(764, 'Currently Not Installed!', NULL),
(765, 'Avalible Lanuages', NULL),
(766, 'PLEASE Read:', NULL),
(767, 'The ZXTS will not have all translation for each language this is becuase it only support core module and not custome/additional ones though it will have the bulk of the translation. So if you install a lanuage that is 100% complete that is relative to core module so may not be 100% complete on your server.', NULL),
(768, 'Percentage Complete', NULL),
(769, 'Currently Installed', NULL),
(770, 'Lanuges', NULL),
(771, 'AjaXplorer', NULL),
(772, 'AjaXplorer v4.2.3 is a powerful file management system created under the Affero GPL License by Charles de Jeu', NULL),
(773, 'Launch AjaXplorer', NULL),
(774, 'APC PHP-Cache', NULL),
(775, 'The Alternative PHP Cache (APC) is a free and open opcode cache for PHP. Its goal is to provide a free, open, and robust framework for caching and optimizing PHP intermediate code.', NULL),
(776, 'Read Me Guide', NULL),
(777, 'Open New Window', NULL),
(778, 'View PHP Cache', NULL),
(779, 'APC Administration Authentication', NULL),
(780, 'On/Off', NULL),
(781, 'APC Shared Memory Segment', NULL),
(782, 'Increase/Decrease APC cache memory limit', NULL),
(783, 'Save Setting', NULL),
(784, 'ZPanelX Module by: JD1pinoy', NULL),
(785, 'AutoIP Updater', NULL),
(786, 'Configure AutoIP Settings', NULL),
(787, 'Current IP', NULL),
(788, 'Detected IP', NULL),
(789, 'Last Update', NULL),
(790, 'Command', NULL),
(791, 'Exec Script', NULL),
(792, 'Email Alert', NULL),
(793, 'Information', NULL),
(794, 'AW Stats', NULL),
(795, 'To view AW stats for a particular domain or subdomain use the drop-down menu to select the domain or sub-domain you want to view. Stats may take up to 24 hours before they are generated.', NULL),
(796, 'Chive', NULL),
(797, 'Chive is a free, open source, web-based database management tool.', NULL),
(798, 'Launch Chive', NULL),
(799, 'DNS Checker', NULL),
(800, 'Reset Query', NULL),
(801, 'Domain Forwarder', NULL),
(802, 'This module enables you to setup and manage domain forwards.', NULL),
(803, 'Delete Forward Domain', NULL),
(804, 'Please confirm that you want to delete this forwarded domain.', NULL),
(805, 'Edit Domain Forward', NULL),
(807, 'Forward Type', NULL),
(808, 'Forward Domain', NULL),
(809, 'To', NULL),
(810, 'Forward www. address for this domain as well', NULL),
(811, 'Forwarded Domains', NULL),
(812, 'Forwarded Domain', NULL),
(813, 'Target Domain', NULL),
(814, 'Include WWW', NULL),
(815, 'There are currently no forwarded domains configured, configure a domain forward below.', NULL),
(816, 'Redirect Protocol', NULL),
(817, 'You have reached the maximum domain forwarders limit', NULL),
(818, 'Unlimited', NULL),
(819, 'Changes to your packages have been saved successfully!', NULL),
(820, 'Automatically update your control panel IP address.', NULL),
(821, 'AutoIPZP(br)Updater', NULL),
(822, 'APCZP(br)PHP-Cache', NULL),
(823, 'AWZP(br)Stats', NULL),
(824, 'DNS Checker Investigate domains and IP addresses.', NULL),
(825, 'DNSZP(br)Checker', NULL),
(826, 'DomainZP(br)Forwarder', NULL),
(827, 'AutoIP<br/>Updater', NULL),
(828, 'APC<br/>PHP-Cache', NULL),
(829, 'AW<br/>Stats', NULL),
(830, 'DNS<br/>Checker', NULL),
(831, 'Domain<br/>Forwarder', NULL);

UPDATE `x_profiles` SET `ud_language_vc` = 'en' WHERE `x_profiles`.`ud_id_pk` =1;

UPDATE `x_accounts` SET `ac_notice_tx` = 'Welcome to your new Sentora installation! You can remove this message from the Client Notice Manager module. This module allows you to notify your clients of service outages upgrades and new features etc :-)' WHERE `x_accounts`.`ac_id_pk` =1;
